### ISSUE TITLE
TinyTeX doesn't include all Beamer theme formatting

### ISSUE THREAD

**Issue by MCM-Math** [yihui/tinytex#100]
I noticed that the Beamer PDFs I generated from R Markdown using TinyTeX were missing the interactive elements for selecting sections and individual slides (I'm not able to include pictures from my work computer).  I compiled the same .tex files using MiKTeX, and they compiled with the elements added.  Therefore, it seems that the issue is with TinyTeX.

**Comment by yihui** [comment]
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)?

**Comment by MCM-Math** [comment]
I did some testing, and it seems that the issue is actually with Pandoc, as Pandoc 2.6 has issues with Beamer, but Pandoc 2.5 does not.
