### ISSUE TITLE
completely remove tinytex

### ISSUE THREAD

**Issue by iembry** [yihui/tinytex#101]
I attempted to install `tinytex` on a GNU/Linux Trisquel distribution, but it interfered with the TeXLive distribution that was already installed so I removed `tinytex` via remove.packages("tinytex").

After `tinytex` should have been removed, I attempted to use `rmarkdown` for a PDF document and this is the result below:
 
/usr/bin/pandoc +RTS -K512m -RTS Key.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Key.tex --template library/rmarkdown/rmd/latex/default.tex --highlight-style kate --latex-engine pdflatex --variable graphics=yes --variable 'compact-title:yes'
Error in loadNamespace(name) : there is no package called ‘tinytex’

How do I completely remove `tinytex` from the system, including from R so that `knitr`/`rmarkdown` do not attempt to locate `tinytex`?

Thank you.

**Comment by yihui** [comment]
The first paragraph in the documentation at https://yihui.name/tinytex/#for-r-users should clear your confusion about TinyTeX vs **tinytex**. You shouldn't remove the latter. The second paragraph tells you how to uninstall TinyTeX.

**Comment by iembry** [comment]
@yihui  Thank you for responding to this issue and for providing the link; however, my problem is still not resolved.

These are the commands that I entered on the command line in GNU/Linux Trisquel (Debian-based distribution):

~$ tlmgr path remove
(running on Debian, switching to user mode!)
action `path' not supported in usermode!

from user $HOME directory
~$ rm -r "~/.TinyTeX"
rm: cannot remove ‘~/.TinyTeX’: No such file or directory

~$ locate TinyTex
does not locate anything

Do you have any other suggestions?

After I entered those commands on the command line, I attempted to use `rmarkdown` for the same PDF document again and I still received the same error message as in the first comment.

Thank you.

**Comment by iembry** [comment]
@yihui  This is the message that I had originally received when I attempted to install `tinytex`:

    > tinytex::install_tinytex()
    (running on Debian, switching to user mode!)
    tlmgr revision 32912 (2014-02-08 00:49:53 +0100)
    tlmgr using installation: /usr/share/texlive
    TeX Live (http://tug.org/texlive) version 2013
    
    Error: Detected an existing tlmgr at /usr/bin/tlmgr. It seems TeX Live has been installed (check 
    tinytex::tinytex_root()). You have to uninstall it, or use install_tinytex(force = TRUE) if you are
    sure TinyTeX can override it (e.g., you are a PATH expert or installed TinyTeX previously).

After I received that message, then I used `remove.packages("tinytex")`. After I could not use `rmarkdown` on the PDF document, I decided to contact you about removing `tinytex` from my system, hence this comment thread.

Thank you for your suggestions. After performing your suggestions, I was able to use `rmarkdown` on the PDF document.

I would suggest breaking up this paragraph and having the information about uninstalling `tinytex` in its own code block:

> What install_tinytex() does will be explained later. If you need to uninstall TinyTeX, run tinytex::uninstall_tinytex(). To compile an R Markdown document to PDF, there is nothing else you have to know. To compile a LaTeX document to PDF, call one of these functions (depending on the LaTeX engine you want to use) in tinytex: pdflatex(), xelatex(), and lualatex(). When these functions detect LaTeX packages required but not installed in TinyTeX, they will automatically install the missing packages by default.

**Comment by yihui** [comment]
Good suggestion. Thanks!

BTW, if you install the current development version of TinyTeX, you will no longer receive an error (but a warning instead) if there is another LaTeX distribution in your system.
