### ISSUE TITLE
Different installation folder

### ISSUE THREAD

**Issue by Galex1223** [yihui/tinytex#104]
Hi Yihui, 
I have yet to try your package, but I'm really eager to and have questions before starting.

My main question is : Do you think it would be possible to use many TinyTeX installations (one for each project)? In other words, would it be possible to install it in my project's home folder and use it as _"virtual environment"_ to keep everything separated from other projects?

I don't know if i'm being clear, but I would use it a bit like python's pip in virtual environment to make it easier to share projects between users and computers !

I took a look at your install_unx.sh file. I know I can change the installation folder but before trying it and mess up everything I wanted to ask what you think, and what would happen under the hood because I'm not savvy enough to know and understand everything that would happens.

**Comment by yihui** [comment]
The answer is yes. See FAQ 8 and 9: https://yihui.name/tinytex/faq/ Instead of `tlmgr path add`, you will need to add the bin path of TinyTeX to the `PATH` variable for each project.

That said, I doubt if it is worth the trouble. LaTeX packages are relatively stable. Anyway, if you want to keep a separate version for each project, that is certainly doable. It is totally up to you.

**Comment by Galex1223** [comment]
Perfect ! I tried just installing it normally while waiting for your answer .... It was so wonderful ! It's exactly what I needed ! I'll tell it to all the people I know who use TeX.

Thank you for your work !

**Comment by yihui** [comment]
No problem. Just let me know if you need further help. Thanks!

**Comment by Galex1223** [comment]
@yihui If you don't mind me asking, I'm just curious : Do you have any future plans or features you want to implement or is it in it's final state and there will only be maintenance ?

**Comment by yihui** [comment]
I'd say TinyTeX is quite mature now. The R wrapper package **tinytex** is also relatively mature. I don't have any specific future plans, but I'm totally open to new features (and of course, I'll continue to fix bugs).

**Comment by Galex1223** [comment]
Hi, it's me again ! 

So I've had time to play a bit with your scripts ! I successfully modified them in order to install it in a venv, wherever this venv is. However, when I try to use `tlmgr`, it does :
`$ tlmgr search "test"`
`bash: /home/galex/bin/tlmgr: No such file or directory`
The weirdest is that running `which tlmgr` correctly points to the venv's bin.

I've also tried :
`$ tlmgr path remove`
which resulted in the same : 
`bash: /home/galex/bin/tlmgr: No such file or directory`

The error is probably something somewhere that I did not understand correctly !
[Here are the modified files](https://github.com/yihui/tinytex/files/2981505/install-tinytex.zip) (only install-unx and install-base have been changed), if you want to have a look at them.

 

I hope you can help me ! 
Thank you again for your time !

**Comment by yihui** [comment]
Sounds like the symbolic link was broken, but I cannot think of a reason why it could be broken. Verify it by:

```sh
ls -l /home/galex/bin/tlmgr
```

**Comment by Galex1223** [comment]
`$ ls -l /home/galex/bin/tlmgr`
`ls: cannot access '/home/galex/bin/tlmgr': No such file or directory`

However, running : ` $ ls -l .venv/bin/tlmgr ` which is where the bin files are in the virtual environment returns 
`lrwxrwxrwx 1 galex galex 86 Mar 18 23:49 .venv/bin/tlmgr -> /home/galex/Path/to/the/venvHome/.venv/.TinyTeX/bin/x86_64-linux/tlmgr`

Everything else seems to work, I've compiled a simple `Hello World!` with xelatex in the venv and it was fine.

**Comment by Galex1223** [comment]
Forget it ! It works ! 

I just tried uninstalling the "regular" installation and I think it fixed the symlinks ! It may be because during my tests, I forgot or could not run `tlmgr path remove` before removing the folders ! Now that I did, it works perfectly fine !
