### ISSUE TITLE
tlmgr_search fails on r-hub debian

### ISSUE THREAD

**Issue by hughjonesd** [yihui/tinytex#105]
tlmgr_search fails on a debian Docker image from R-hub (using r-devel) with the following error message:

```
> tlmgr_search("siunitx")
tlmgr search --file --global 'siunitx'
(running on Debian, switching to user mode!)
Cannot determine type of tlpdb from /home/docker/texmf!
tlmgr: running in usermode, did you call `tlmgr init-usertree'?
```

This causes automatic package installation to break.

My session info:

```
> xfun::session_info('rmarkdown')
R Under development (unstable) (2019-03-11 r76221)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
  LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3 digest_0.6.18   evaluate_0.13   glue_1.3.1     
  graphics_3.6.0  grDevices_3.6.0 highr_0.7       htmltools_0.3.6
  jsonlite_1.6    knitr_1.22      magrittr_1.5    markdown_0.9   
  methods_3.6.0   mime_0.6        Rcpp_1.0.0      rmarkdown_1.12 
  stats_3.6.0     stringi_1.4.3   stringr_1.4.0   tinytex_0.11   
  tools_3.6.0     utils_3.6.0     xfun_0.5        yaml_2.2.0     
```

I don't have the same problem on OS X using R 3.5.2.

Indeed, manually running `tlmgr init-usertree` seems to fix the problem.

**Comment by yihui** [comment]
You (or the creator of R-hub) are recommended to install TinyTeX instead of Debian's own texlive-* packages, because TinyTeX doesn't require `sudo`, which makes is much easier to manage LaTeX packages.

**Comment by hughjonesd** [comment]
I get it. But I suspect that R-hub also wants to track CRAN closely. CCing @r-hub.

(Off-topic: I feel as if CRAN is the source of much evil, along with all its good.)

**Comment by yihui** [comment]
I have intentionally left an argument `usermode` in `tlmgr_install()` for this case, but I'm really not interested in supporting Debian's pre-packaged texlive, even though I think I roughly know how to do it. If you can figure it out, you are welcome to submit a PR. Thanks!
