### ISSUE TITLE
Installation error - fails to install pdflatex.exe

### ISSUE THREAD

**Issue by jsdel** [yihui/tinytex#107]
Hi, 
I am unable to install TinyTeX successfully into a user-specified directory on Windows 10.

Printed out during installation, I see the following snippets:
Installing TeX Live 2018 from: http://mirror.aarnet.edu.au/pub/CTAN/systems/texlive/tlnet (not verified)

Cannot open ./TinyTeX/texmf-config/ls-R to write.
Cannot open ./TinyTeX/texmf-dist/ls-R to write.
mktexlsr: Done.
running updmap-sys --nohash ...D:\Users\XXXXXXXX\AppData\Local\Temp\51\RtmpSY9Q8O\install-tl-20190227\install-tl: updmap-sys --nohash failed (status 53): 
failed
re-running mktexlsr ./TinyTeX/texmf-var ./TinyTeX/texmf-config ...
mktexlsr: Updating ./TinyTeX/texmf-var/ls-R...
mktexlsr: Updated ./TinyTeX/texmf-var/ls-R.
Cannot open ./TinyTeX/texmf-config/ls-R to write.
mktexlsr: Done.
pre-generating all format files, be patient...
running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all ...D:\Users\XXXXXXXX\AppData\Local\Temp\51\RtmpSY9Q8O\install-tl-20190227\install-tl: fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all failed (status 53): 

D:\Users\XXXXXXXX\AppData\Local\Temp\51\RtmpSY9Q8O\install-tl-20190227\install-tl: errors in installation reported above

Summary of warnings:
D:\Users\XXXXXXXX\AppData\Local\Temp\51\RtmpSY9Q8O\install-tl-20190227\install-tl: updmap-sys --nohash failed (status 53): 
D:\Users\XXXXXXXX\AppData\Local\Temp\51\RtmpSY9Q8O\install-tl-20190227\install-tl: fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all failed (status 53): 
failed
running package-specific postactions
finished with package-specific postactions

Welcome to TeX Live!

L:\MYPATH\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl: TLPDB::from_file could not download http://mirror.aarnet.edu.au/pub/CTAN/systems/texlive/tlnet/tlpkg/texlive.tlpdb;
L:\MYPATH\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl: maybe the repository setting should be changed.
Use of uninitialized value in bitwise or (|) at L:\MYPATH\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 1482.
TinyTeX installed to L:\MYPATH\TinyTeX
Please restart your R session and IDE (if you are using one, such as RStudio or Emacs) and check if tinytex:::is_tinytex() is TRUE.

After restart, I get:
tinytex:::is_tinytex()
[1] TRUE

And the following is in my PATH:
L:\\MYPATH\\TinyTeX\\bin\\win32

But when trying to export an .Rmd I get:
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS foo.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output foo.pdf --template "C:\PROGRA~1\R\R-35~1.1\library\RMARKD~1\rmd\latex\DEFAUL~3.TEX" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" 
pandoc.exe: pdflatex not found. pdflatex is needed for pdf output.
Error: pandoc document conversion failed with error 41
Execution halted

No TeX installation detected (TeX is required to create PDF output). You should install a recommended TeX distribution for your platform:

  Windows: MiKTeX (Complete) - http://miktex.org/2.9/setup
  (NOTE: Be sure to download the Complete rather than Basic installation)

  Mac OS X: TexLive 2013 (Full) - http://tug.org/mactex/
  (NOTE: Download with Safari rather than Chrome _strongly_ recommended)

  Linux: Use system package manager

I have tried re-installing everything from scratch a couple of times without luck. I should also mention that the L: drive I am installing to is a network path and I do not have administrator rights. Finally:

> Sys.which('pdflatex')
pdflatex 
      "" 

So pdflatex.exe is not being installed. I am not sure what else to try. Thanks for any suggestions.
Steve

**Comment by jsdel** [comment]
Hi, 
In case it helps, here is the session info. Please also note that I am not able to upgrade R on this server.

> xfun::session_info('rmarkdown')
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200), RStudio 1.1.463

Locale:
  LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
  LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
  LC_TIME=English_Australia.1252    

Package version:
  backports_1.1.2 base64enc_0.1.3 digest_0.6.18   evaluate_0.12  
  glue_1.3.0      graphics_3.5.1  grDevices_3.5.1 highr_0.7      
  htmltools_0.3.6 jsonlite_1.5    knitr_1.20      magrittr_1.5   
  markdown_0.8    methods_3.5.1   mime_0.6        Rcpp_1.0.0     
  rmarkdown_1.10  rprojroot_1.3.2 stats_3.5.1     stringi_1.2.4  
  stringr_1.3.1   tinytex_0.9     tools_3.5.1     utils_3.5.1    
  xfun_0.4        yaml_2.2.0

**Comment by yihui** [comment]
R 3.5.1 is fine, but several of your R packages are not their latest CRAN versions. Please update all packages: https://yihui.name/en/2017/05/when-in-doubt-upgrade/
