### ISSUE TITLE
install-base.sh doesnt follow repository argument

### ISSUE THREAD

**Issue by aubreybailey** [yihui/tinytex#108]
https://raw.githubusercontent.com/yihui/tinytex/master/tools/install-base.sh
is hard coded to 
"http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"
and therefore cant respect the arguments passed to
install_tinytex(repository="<my_mirror>")

**Comment by yihui** [comment]
That's right. Do you have any issues with downloading from http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz?

**Comment by aubreybailey** [comment]
Yes, the mirror in Finland is currently misdirecting, and not automatically
finding another host. I have been in contact with the owners and they are
working on it, but others, i.e. China may not be able to select the correct
mirror if the default routing fails.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

Example:

```r
tinytex::install_tinytex(repository = 'https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet')
```

**Comment by aubreybailey** [comment]
Perfect! Thanks!
