### ISSUE TITLE
TinyTex and Auxtex/Emacs on OSX

### ISSUE THREAD

**Issue by nickp60** [yihui/tinytex#11]
Hi,
This is a long shot but has anyone managed to get TinyTex to cooperate with Auctex/Emacs on OSX?  I had no major issues on Unbuntu other than needing to adjust emacs's PATH, but I have had no luck on OSX.  I'm using emacs installed from Homebrew...

**Comment by yihui** [comment]
Symlinks are made to `/usr/local/bin` on macOS, so there should not be a reason why Emacs cannot find them.

**Comment by nickp60** [comment]
Yeah, its a weird one;  I suspect Auctex has some strange checks for executables.  Running BibTeX works fine, and generating a preview mostly works, so it feels like some other issue with how it is searching the PATH.  Feel free to close this issue; but I would be interested to hear if there are any workarounds...

**Comment by yihui** [comment]
I'm fine with leaving this issue open for a while.

**Comment by skiyer** [comment]
According to the AUCTex source code , I've found this issue is related to the TeX-check-TeX variable. My workaround is to set TeX-check-TeX to nil in AUCTex's customize-group.

**Comment by nickp60** [comment]
That worked for me!!!!  I added `(sets TeX-check-TeX  `nil)` to my init, and that seems to have done the trick!  Thanks so much!

**Comment by yihui** [comment]
Excellent. Thanks a lot, @skiyer!
