### ISSUE TITLE
关于tlmgr自身问题导致 tinytex适应能力不强

### ISSUE THREAD

**Issue by bubifengyun** [yihui/tinytex#110]
不好意思，英文太烂了。试着用 tinytex通过tlmgr安装一些texlive的包。但总是提示错误。后来直接安装texlive2018就可以了。比如关于 https://github.com/sjtug/SJTUThesis/issues/409#issuecomment-478310694 这里反映的问题。有没有啥办法避免这个问题，可以更好的采用联网一键安装 tinytex 及其相应的包，而不是不安装texlive就报错。非常感谢。

**Comment by yihui** [comment]
请提供一个简化到不能再简化的可重复例子。

**Comment by ifendo** [comment]
hi yihui, 我昨天也碰到了一个问题
tinytex:::tinytex:::is_tinytex() return TRUE, 但是生成pdf_output 总是pdflatex not found. 之前老版本是可以的

xfun::session_info()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393), RStudio 1.2.1335

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 compiler_3.5.2  digest_0.6.18   evaluate_0.13   glue_1.3.1      graphics_3.5.2 
  grDevices_3.5.2 highr_0.7       htmltools_0.3.6 jsonlite_1.6    knitr_1.22      magrittr_1.5   
  markdown_0.9    methods_3.5.2   mime_0.6        Rcpp_1.0.0      rmarkdown_1.11  stats_3.5.2    
  stringi_1.4.3   stringr_1.4.0   tinytex_0.11    tools_3.5.2     utils_3.5.2     xfun_0.5.1     
  yaml_2.2.0     

不好意思，另外还有一个问题，貌似最新版默认tinytex::install_tinytex()  到最后一步会报错
rsession.exe 被Trend Micro\OfficeScan Client当作木马拦截了，我有截图但是不知道怎么发上来:(

**Comment by ifendo** [comment]
`tinytex:::install_prebuilt()`解决了我的问题
![image](https://user-images.githubusercontent.com/10232854/55773827-1e9a5a00-5ac5-11e9-9b34-938a15c20471.png)
![image](https://user-images.githubusercontent.com/10232854/55773830-21954a80-5ac5-11e9-9388-ea52b62ef5f4.png)

拦截问题不知道其他人有没有，放上来给参考下

**Comment by SimonZYC** [comment]
我直接将所有的包装上：
```
tlmgr install scheme-full
```
然后按照官网：
```
tlmgr update --self --all
tlmgr path add
fmtutil-sys --all
```
基本上用起来没有问题，总大小在3G左右。

**Comment by bubifengyun** [comment]
我也参照了，https://github.com/yihui/tinytex/issues/103 ，但是报错，就是那个 http https的问题，我安装的 3.6.0说是无法安装 bookdown，安装的3.5.3 又无法安装最新的 tinytex。等待后续更新吧。

**Comment by bubifengyun** [comment]
很抱歉，我发现直接使用 `tinytex`，会导致 tlmgr search --file --global "/gb7714-2015.dbx" 的问题，https://github.com/sjtug/SJTUThesis/issues/409，一直无法解决，我就把`~/bin`下安装的 xelatex 之类的全删了。竟然好了。
