### ISSUE TITLE
latexmk changes working directory

### ISSUE THREAD

**Issue by aj2duncan** [yihui/tinytex#12]
Hi Yihui, 

I have been using `tinytex::latexmk` to compile a .tex file in a subdirectory of my working directory. I'm working within an RStudio project as all my analysis is in R and I keep the working directory to the top level folder, working relative to that. The file compiles fine and I really like the automatic finding of missing packages. However, `tinytex::latemk` changes the working directory to that of the .tex file (which makes sense) but doesn't change it back. 

It isn't causing a problem as it is straight forward to work around but it wasn't what I thought would happen, apologies if I missed something in the docs. If this is by design that's also not a problem but I wonder if other users might run into this.

I have attached a .zip file with an example. Running the code in `tinytex_wd_demo.r` will hopefully reproduce things. 

[tinytex_wd.zip](https://github.com/yihui/tinytex/files/1638840/tinytex_wd.zip)

```{r}
sessionInfo()
```

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16    tinytex_0.2.11
```

Thanks for your time and all of your excellent work.

**Comment by yihui** [comment]
Okay, I figured it out. I was bitten by the `on.exit()` problem again: https://yihui.name/en/2017/05/a-note-on-on-exit/ Thanks for the report as well as the excellent minimal reproducible example! 👍
