### ISSUE TITLE
Issue removing platform-specifc string from installed LaTeX Packages

### ISSUE THREAD

**Issue by riccardoporreca** [yihui/tinytex#120]
As mentioned in `help("tl_pkgs")`
> Platform-specific strings in package names are removed, e.g., "tex" is returned for the package tex.x86_64-darwin.

However, this is implemented by removing everything after the first dot 
https://github.com/yihui/tinytex/blob/84660e0dbbac60d63313a8d3b8cfd30a7382d68d/R/tlmgr.R#L223
assuming the dot is not part of any package name. This is however the case for e.g. `texlive.infra`, which is then converted to `texlive`.

``` r
grep("texlive", tinytex::tl_pkgs(), value = TRUE)
#> [1] "texlive" "texlive"
grep("texlive", tinytex:::tl_list(stdout = TRUE, .quiet = TRUE), value = TRUE)
#> [1] "texlive.infra"              "texlive.infra.x86_64-linux"
xfun::session_info('tinytex')
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 18.04.2 LTS
#> 
#> Locale:
#>   LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>   LC_TIME=de_CH.UTF-8        LC_COLLATE=en_US.UTF-8    
#>   LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>   LC_PAPER=de_CH.UTF-8       LC_NAME=C                 
#>   LC_ADDRESS=C               LC_TELEPHONE=C            
#>   LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       
#> 
#> Package version:
#>   tinytex_0.13.3 tools_3.6.0    xfun_0.7
```
Note that `texlive` is not a LaTeX package, which causes e.g. `reinstall_tinytex()` to display error `tlmgr install: package texlive not present in repository`, and not including `texlive.infra` among the packages to be re-installed.

Not sure if there is an easier way around this, but one option could be to rely on `tlmgr platform list` to determine the installed (or all) platforms and remove them explicitly. Quick try in R (could become an internal function `tl_platform_list()`)
``` r
sub("^\\s*\\(i\\)\\s*", "",
    grep("^\\s*\\(i\\)\\s*", 
         tinytex::tlmgr(c("platform", "list"), stdout = TRUE, .quiet = TRUE),
         value = TRUE))
#> [1] "x86_64-linux"
```
and at the terminal (needed e.g.  when creating `TL_INSTALLED_PKGS` as in the [FAQ](https://yihui.name/tinytex/faq/))
``` bash
tlmgr platform list | grep -E '^\s*\(i\)' | sed -E 's/^\s*\(i\)\s+//'
## x86_64-linux
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
Thanks a lot for filing the issue and also providing a possible fix! I'll take care of it.

**Comment by riccardoporreca** [comment]
Thanks to you @yihui, this is basically a follow-up on [your hint](https://github.com/yihui/tinytex/issues/118#issuecomment-492797830) about installing (now also re-installing) TinyTeX and LaTeX packages a-la rocker/verse, which we have been happily integrating in stand-alone scripts [SmaRP/docker/install_tinytex.sh](https://github.com/miraisolutions/SmaRP/blob/b5643d6772defc109565731c96a4ea49c6f19197/docker/install_tinytex.sh), [SmaRP/docker/reinstall_tinytex.sh](https://github.com/miraisolutions/SmaRP/blob/b5643d6772defc109565731c96a4ea49c6f19197/docker/reinstall_tinytex.sh), the latter already using the `tlmgr platform list` trick.

**Comment by yihui** [comment]
Should be fixed now. I used `tlmgr print-platform` to obtain the platform identifier. Thanks again for the report!
