### ISSUE TITLE
tlmgr to install missing Latex pkgs from locally stored .zip

### ISSUE THREAD

**Issue by antoinecollet5** [yihui/tinytex#126]
Dear Yihui,

Just a short question.

I was not able to get the right synthax to install TinyTex missing Latex packages from local.zip. I do not have the choice, because of my company firewall. 
I tried in R using `tinytex::tlmgr_install`, but it is obvouisly not the right one:

```
tlmgr install C:\Users\ancollet\Documents\7 - Software\R\Installation_float\float.zip
tlmgr.pl install: package - not present in repository.
tlmgr.pl install: package C:\Users\ancollet\Documents\7 not present in repository.
tlmgr.pl install: package Software\R\Installation_float\float.zip not present in repository.
tlmgr.pl: action install returned an error; continuing.
No connection to the internet.
Unable to download the checksum of the remote TeX Live database,
but found a local copy so using that.

You may want to try specifying an explicit or different CTAN mirror;
see the information and examples for the -repository option at
https://tug.org/texlive/doc/install-tl.html
(or in the output of install-tl --help).

tlmgr.pl: package repository http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet (not verified: unknown)
tlmgr.pl: An error has occurred. See above messages. Exiting.
```

What should be the correct one ? I tried to understand from the [tlmgr guide](https://www.tug.org/texlive/doc/tlmgr.html#install-option...-pkg), but I am a bit lost with the syntax and these concepts of repository etc.

I also tried to install the package directly to TinyTex in my appdata folder, unfortunately, I am not able to idendity the right "TEXMFHOME" directory to place my .sty and .pdf.
In a windows CMD, it gives me:
```
>kpsewhich -var-value TEXMFHOME
$HOM./TinyTex/.TinyTe./TinyTex/texmf-home
```

Thank you in advance :)

**Comment by antoinecollet5** [comment]
Finally I succeed using the second method:

I placed the float.zip (downloaded from [CTAN](https://ctan.org/pkg/float)) in the `\AppData\Roaming\TinyTeX\texmf-local\tex\latex` directoty and unziped it.
I opened a windows shell and placed myself in the new `\AppData\Roaming\TinyTeX\texmf-local\tex\latex\float` directory and ran the following lines to  obtain the .sty
```
> pdflatex float.dtx
> latex float.ins
```
Along the float.sty file, a float.pdf was created and I placed it in the following directory: `\AppData\Roaming\TinyTeX\texmf-local\doc\float` 
It was then necessary to update the file database, using that line in the windows shell:
`> mktexlsr`

The missing float package is now recognize by TinyTex and I can compile my Rmarkdown loading the Tex package from Rstudio.

However, if you have a simpler way, using directly tlmgr, I am interested :)

**Comment by yihui** [comment]
From https://www.tug.org/texlive/doc/tlmgr.html#install-option...-pkg, it seems you have to use the `--file` argument, but the `tlmgr` documentation is not very clear to me about what value we should pass to `--file`. Could it be a zip file? If so, the corresponding call in R would be

```r
tinytex::tlmgr(c('install, '--file', shQuote('float.zip'))
```

Anyway, you can certainly manually unzip the package file to the TinyTeX directory as you did above.
