### ISSUE TITLE
File `l3backend-xdvipdfmx.def' not found; need install `l3backend` manually

### ISSUE THREAD

**Issue by uninyhart** [yihui/tinytex#127]
Using package `l3kernel` (version 2019-07-01), it needs to install `l3backend` manually.

If not, it will report an error:

```
! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.
```

It influences package `fontspec` and packages based on it.

最近更新的宏包 `l3kernel`（版本 2019-07-01），会报错：

```
! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.
```

这会影响到 `fontspec` 宏包以及 `ctex` 等基于 `fontspec` 的宏包。

需要手动安装 `l3backend` 解决这个问题。

**Comment by yihui** [comment]
If you are an R user, the missing LaTeX package will be automatically installed. If you are not an R user, you need to read the documentation: https://yihui.name/tinytex/

**Comment by uninyhart** [comment]
`l3backend` 并不会被自动安装，因为

```bash
tlmgr search --global "./l3backend-xdvipdfmx.def"
```

是没有搜索结果的。

如果看 `l3backend-xdvipdfmx.def` 的源码

```
%% This is file `l3backend-xdvipdfmx.def',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% l3backend-basics.dtx  (with options: `package,xdvipdfmx')
%% l3backend-color.dtx  (with options: `package,xdvipdfmx')
%% l3backend-box.dtx  (with options: `package,xdvipdfmx')
%% l3backend-draw.dtx  (with options: `package,xdvipdfmx')
%% l3backend-graphics.dtx  (with options: `package,xdvipdfmx')
%% l3backend-pdf.dtx  (with options: `package,xdvipdfmx')
```

它是自动生成的，所以在 CTAN 上直接搜是搜不到的，这就很尴尬了。

因为 `fontspec` 被大量中文用户使用，所以很有可能使用 TinyTeX 的用户会碰到这个问题，所以留一个 Issue。

大部分宏包可以通过搜索解决，然而，有些文件真的很难搜到（需要黑魔法）……这是我用了 TinyTeX 一年的感想……

**Comment by yihui** [comment]
会搜到的：

```r
tinytex::parse_packages(text = "! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.")
# tlmgr search --file --global '/l3backend-xdvipdfmx.def'
# [1] "l3backend"
```

**Comment by uninyhart** [comment]
呃，好吧，很抱歉，还真搜的到。

我是直接在 CTAN 上搜文件的，所以搜不到。（感觉太蠢了）

Close.

**Comment by yihui** [comment]
没事。

**Comment by Amazingren** [comment]
> 呃，好吧，很抱歉，还真搜的到。
> 
> 我是直接在 CTAN 上搜文件的，所以搜不到。（感觉太蠢了）
> 
> Close.

所以到底该怎么解决啊~直接在CTAN上搜索就行了吗，你搜索的管检测是什么啊

**Comment by Amazingren** [comment]
> ```r
> ! LaTeX Error: File `l3backend-xdvipdfmx.def' not found
> ```

我搜索`! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.`不行
搜索`l3backend-xdvipdfmx.def`也不行啊，想问一下该怎么办哦~

**Comment by yihui** [comment]
所以你是怎么撞上这个问题的、以及看没看我上面的回复啊？我的第一个回复说，如果你是 R 用户，你几乎不可能撞上这个问题；第二个回复告诉了你如何从错误消息搜包。

**Comment by MarkErik** [comment]
Hi, I believe that I am also having a problem with this, here is the output in the RStudio console:

tlmgr search --file --global '/l3backend-xdvipdfmx.def'
Trying to automatically install missing LaTeX packages...
tlmgr install l3backend
tlmgr: package repository https://mirror-hk.koddos.net/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package already present: l3backend
tlmgr path add
tlmgr search --file --global '/l3backend-xdvipdfmx.def'
! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.

! Emergency stop.
<read *>

**Comment by yihui** [comment]
@MarkErik Could you read and follow [the issue guide](new) exactly to provide all the required information? Thanks!

**Comment by Amazingren** [comment]
> Hi, I believe that I am also having a problem with this, here is the output in the RStudio console:
> 
> tlmgr search --file --global '/l3backend-xdvipdfmx.def'
> Trying to automatically install missing LaTeX packages...
> tlmgr install l3backend
> tlmgr: package repository https://mirror-hk.koddos.net/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
> tlmgr install: package already present: l3backend
> tlmgr path add
> tlmgr search --file --global '/l3backend-xdvipdfmx.def'
> ! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.
> 
> ! Emergency stop.
> <read *>

你把文件名字改成英文就好了

**Comment by pzhaonet** [comment]
I got this problem today. This file could not be found when running `tinytex::parse_packages(text = "! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.")`, and it showed:
```
tlmgr.pl: Local TeX Live (2018) is older than remote repository (2019).
```

even `tinytex::tlmgr_update()` could not solve the problem. Luckily, I reinstalled TinyTeX via `tinytex::reinstall_tinytex()`, and the problem was gone.

**Comment by yihui** [comment]
@pzhaonet Yes, you have to reinstall TinyTeX every year (usually in April or May) if you need to install any new LaTeX packages: https://yihui.name/tinytex/#maintenance
