### ISSUE TITLE
`xdvipdfmx:fatal: Unable to find TFM file "<font-file-name>"`; sometimes need install font packages manually

### ISSUE THREAD

**Issue by uninyhart** [yihui/tinytex#129]
## 描述

有一种报错是缺字体，在最后一步使用 `xdvipdfmk` 转成 PDF 文件的时候可能会有

```
xdvipdfmx:fatal: Unable to find TFM file "<font-file-name>".
```

这个时候 TinyTeX 检测不到，需要手动安装。

## 样例

比如使用 `mathptmx` 宏包

```latex
\documentclass{article}

\usepackage{mathptmx}

\begin{document}    

$\mathcal{A}$

\end{document}  
```

在这里使用 `\mathcal` 需要额外安装字体宏包 `rsfs`。

如果使用 `pdflatex` 编译报错：

```
! Font \csname\endcsname=rsfs10 at 10.0pt not loadable: Metric (TFM) file not found.
```

在这里如果使用 `tinytex::pdflatex` 编译是可以成功安装 `rsfs`。

然而如果使用 `tinytex::xelatex` 不会报错，直接输出损坏的 PDF 文件。

如果使用 `latexmk -xelatex` 编译报错：

```
xdvipdfmx:fatal: Unable to find TFM file "rsfs10".
```

**Comment by yihui** [comment]
已修正。谢谢！
