### ISSUE TITLE
tinytex::tlmgr_path() retuns:

### ISSUE THREAD

**Issue by solomoncharles77** [yihui/tinytex#134]
tinytex::tlmgr_path() retuns:

tlmgr path add
Dit programma wordt geblokkeerd door Groepsbeleid. Neem voor meer informatie contact op met de systeembeheerder.
Warning message:
running command '"tlmgr" path add' had status 1 

Based on the above we think that our IT department has blocked the system command setx. We also couldn't modify the (system) PATH variable using the link you provided. However, we can add it to our accounts specifically causing the "No TeX installation detected" error to disappear.

Unfortunately, we still get the following errors when trying to Knit a PDF document:

output file: asdf.knit.md

Error: Failed to compile asdf.tex.
In addition: Warning messages:
1: running command '"pdflatex" -halt-on-error -interaction=batchmode "asdf.tex"' had status 127 
2: running command '"pdflatex" -halt-on-error -interaction=batchmode "asdf.tex"' had status 127 
Execution halted

Given the fact that our IT department blocked the "tlmgr path add" command, could it be that they also block pdflatex.exe? If so, is there still a way to generate PDF's using TinyTex? :)

_Originally posted by @karstendevries in https://github.com/yihui/tinytex/issues/79#issuecomment-431767532_

**Comment by solomoncharles77** [comment]
Hi Yui, I have a similar issue. However when I run `tinytex::tlmgr_path()` I get the following ; 
Warning message:
In tlmgr(c("path", match.arg(action))) :
  TeX Live does not seem to be installed. See https://yihui.name/tinytex/.

I don't know how to continue

`tinytex::install_tinytex()`
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
Content length 347 bytes
downloaded 21.5 MB

trying URL 'https://yihui.name/gh/tinytex/tools/pkgs-custom.txt'
Content length 81 bytes
downloaded 318 bytes

trying URL 'https://yihui.name/gh/tinytex/tools/tinytex.profile'
Content length 81 bytes
downloaded 295 bytes

Starting to install TinyTeX to \\uol.le.ac.uk\root\staff\setting\w7\C\cus2\AppData\Roaming/TinyTeX. It will take a few minutes.
Automated TeX Live installation using profile: ../tinytex.profile
Loading http://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/texlive/tlnet/tlpkg/texlive.tlpdb
Installing TeX Live 2019 from: http://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/texlive/tlnet (not verified)
Platform: win32 => 'Windows'
Distribution: net  (downloading)
Using URL: http://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/texlive/tlnet
Directory for temporary files: C:\Users\cus2\AppData\Local\Temp\0_SuuN7vXd
Installing to: ./TinyTeX/
Installing [01/10, time/total: ??:??/??:??]: hyphen-base [22k]
Installing [02/10, time/total: 00:03/39:21]: kpathsea [31k]
Installing [03/10, time/total: 00:04/21:48]: kpathsea.win32 [497k]
Installing [04/10, time/total: 00:05/02:36]: tetex [71k]
Installing [05/10, time/total: 00:07/03:14]: tetex.win32 [1k]
Installing [06/10, time/total: 00:08/03:42]: texlive.infra [212k]
Installing [07/10, time/total: 00:09/03:06]: texlive.infra.win32 [1391k]
Installing [08/10, time/total: 00:12/01:33]: tlgs.win32 [6642k]
Installing [09/10, time/total: 00:15/00:29]: tlperl.win32 [6960k]
Installing [10/10, time/total: 00:23/00:25]: tlpsv.win32 [1411k]
Time used for installing the packages: 00:25
running mktexlsr ./TinyTeX/texmf-dist ...
mktexlsr: Updating ./TinyTeX/texmf-dist/ls-R...
mktexlsr: Updated ./TinyTeX/texmf-dist/ls-R.
mktexlsr: Done.
writing fmtutil.cnf to ./TinyTeX/texmf-dist/web2c/fmtutil.cnf
writing updmap.cfg to ./TinyTeX/texmf-dist/web2c/updmap.cfg
writing language.dat to ./TinyTeX/texmf-var/tex/generic/config/language.dat
writing language.def to ./TinyTeX/texmf-var/tex/generic/config/language.def
writing language.dat.lua to ./TinyTeX/texmf-var/tex/generic/config/language.dat.lua
running mktexlsr ./TinyTeX/texmf-var ./TinyTeX/texmf-config ./TinyTeX/texmf-dist ...
mktexlsr: Updating ./TinyTeX/texmf-var/ls-R...
mktexlsr: Updated ./TinyTeX/texmf-var/ls-R.
Cannot open ./TinyTeX/texmf-config/ls-R to write.
Cannot open ./TinyTeX/texmf-dist/ls-R to write.
mktexlsr: Done.
running updmap-sys --nohash ...C:\Users\cus2\AppData\Local\Temp\Rtmpgp7FA6\install-tl-20190716\install-tl: updmap-sys --nohash failed (status 53): 
failed
re-running mktexlsr ./TinyTeX/texmf-var ./TinyTeX/texmf-config ...
mktexlsr: Updating ./TinyTeX/texmf-var/ls-R...
mktexlsr: Updated ./TinyTeX/texmf-var/ls-R.
Cannot open ./TinyTeX/texmf-config/ls-R to write.
mktexlsr: Done.
pre-generating all format files, be patient...
running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all ...C:\Users\cus2\AppData\Local\Temp\Rtmpgp7FA6\install-tl-20190716\install-tl: fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all failed (status 53): 

C:\Users\cus2\AppData\Local\Temp\Rtmpgp7FA6\install-tl-20190716\install-tl: errors in installation reported above

Summary of warnings:
C:\Users\cus2\AppData\Local\Temp\Rtmpgp7FA6\install-tl-20190716\install-tl: updmap-sys --nohash failed (status 53): 
C:\Users\cus2\AppData\Local\Temp\Rtmpgp7FA6\install-tl-20190716\install-tl: fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all failed (status 53): 

 ----------------------------------------------------------------------
 The following environment variables contain the string "tex"
 (case-independent).  If you're doing anything but adding personal
 directories to the system paths, they may well cause trouble somewhere
 while running TeX.  If you encounter problems, try unsetting them.
 Please ignore spurious matches unrelated to TeX.

    II=C:\Users\cus2\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\
 ----------------------------------------------------------------------
failed
running package-specific postactions
finished with package-specific postactions


Welcome to TeX Live!


See ./TinyTeX//index.html for links to documentation.
The TeX Live web site (https://tug.org/texlive/) contains any updates and
corrections. TeX Live is a joint project of the TeX user groups around the
world; please consider supporting it by joining the group best for you. The
list of groups is available on the web at https://tug.org/usergroups.html.
Logfile: ./TinyTeX/install-tl.log
Error in file.copy(list.files("TinyTeX", full.names = TRUE), target, recursive = TRUE) : 
  more 'from' files than 'to' files
Please quit and reopen your R session and IDE (if you are using one, such as RStudio or Emacs) and check if tinytex:::is_tinytex() is TRUE.

After restarting R

`tinytex:::is_tinytex()`
[1] FALSE


`remotes::install_github('yihui/tinytex', force = TRUE)`
Downloading GitHub repo yihui/tinytex@master
Running `R CMD build`...
* checking for file 'C:\Users\cus2\AppData\Local\Temp\RtmpOoHAgF\remotes144043bc1197\yihui-tinytex-07cea7f/DESCRIPTION' ... OK
* preparing 'tinytex':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'tinytex_0.14.3.tar.gz'
Installing package into ‘Z:/My Documents/R/3.6.1/Library’
(as ‘lib’ is unspecified)
'\\uol.le.ac.uk\root\staff\home\c\cus2\Desktop Files\MyTheses\Thesis'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'tinytex' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'tinytex'
    finding HTML links ... done
    copy_tinytex                            html  
    install_tinytex                         html  
    latexmk                                 html  
    parse_packages                          html  
    r_texmf                                 html  
    tl_pkgs                                 html  
    tl_sizes                                html  
    tlmgr                                   html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (tinytex)
Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

After restarting R
`tinytex:::is_tinytex()`
[1] FALSE

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1, RStudio 1.0.143

Locale:
  LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
  LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
  LC_TIME=English_United Kingdom.1252    

Package version:
  graphics_3.6.1  grDevices_3.6.1 stats_3.6.1     tinytex_0.14.3  tools_3.6.1    
  utils_3.6.1     xfun_0.8

**Comment by yihui** [comment]
1. The R package **tinytex** does not require TinyTeX to be on `PATH`, so it doesn't matter if `tlmgr_path()` fails or your IT disallow `setx`.
1. If `install_tinytex()` fails, you may try `tinytex:::install_prebuilt()`.

**Comment by solomoncharles77** [comment]
Hi Yihui,
No luck with the prebuilt version either.

`tinytex:::install_prebuilt()`
trying URL 'https://ci.appveyor.com/api/projects/yihui/tinytex/artifacts/TinyTeX.zip'
 length 92011403 bytes (87.7 MB)
downloaded 87.7 MB

tlmgr path add
Warning messages:
1: In unzip(path, exdir = win_app_dir()) :
  error -1 in extracting from zip file
2: In tlmgr(c("path", match.arg(action))) :
  TeX Live does not seem to be installed. See https://yihui.name/tinytex/.

**Comment by yihui** [comment]
Sounds like your IT has put too much constraint on your computer and R failed to run `unzip()`. Perhaps you can manually download TinyTeX.zip from the URL in the above message, unzip it, and copy the folder to `tinytex:::win_app_dir()`. If that doesn't work, I'm afraid I won't be able to help further.

**Comment by solomoncharles77** [comment]
> Sounds like your IT has put too much constraint on your computer and R failed to run unzip().

Unfortunately that's the case. Thanks for your kind assistance. Thanks the great packages you've authored.

**Comment by yihui** [comment]
Thank you for your understanding and patience!
