### ISSUE TITLE
Strange Problem `ABD: EverySelectfont initializing macros`

### ISSUE THREAD

**Issue by uninyhart** [yihui/tinytex#137]
环境：

- TeX Live 2019 (TinyTeX)
- Windows 10

测试样例：

```latex
\documentclass{ctexart}

\begin{document}
    
测试测试 Test Test

\end{document}
```

碰到了一次这个错误

```
ABD: EverySelectfont initializing macros
```

貌似是 CTeX 宏包的行为，不过怎么查都查不出原因。

然后，过了一个小时，编译了一下，然后就好了……

**Comment by yihui** [comment]
我没见过这个错误，也不知道该咋整……

**Comment by uninyhart** [comment]
开在这里就当给搜索引擎投食吧，我以前从没有遇到过，就遇到过一次，然后就莫名其妙好了……

**Comment by yihui** [comment]
好的。谢谢！

**Comment by CaoHanyun** [comment]
本人LaTex小白，我是之前的可以正常编译，加上\paragraph 和 \subparagragh 的功能都没问题，然后ctrl-z回退并再此编译之前的，就产生这个报错了orz。不知道为什么。截图如下：
![image](https://user-images.githubusercontent.com/61311604/148246439-1924898a-a54b-4bd5-8fd8-0de538d583be.png)
