### ISSUE TITLE
if there is a way to choose another CTAN mirror?

### ISSUE THREAD

**Issue by ferristale** [yihui/tinytex#14]
especially when installing, the default mirror is slow in mainland China.

**Comment by XiangyunHuang** [comment]
here is a solution <https://d.cosx.org/d/419672-tinytex/62>

**Comment by ferristale** [comment]
@XiangyunHuang Thanks, it's that means the author is planning to add a feature that can change the mirror when installing? 
The time that needed to install tinytex itself is also very long for me.

**Comment by XiangyunHuang** [comment]
the latest version has the feature which you ask，so jupdate your tinytex package

**Comment by yihui** [comment]
In theory, the TeX Live installer should be able to choose a fast mirror automatically, but I don't know why it fails to choose on in your case. Anyway, how long did it take for you to install TinyTeX?

**Comment by yihui** [comment]
Never mind. I just implemented it. You can install the development version via

```r
devtools::install_github('yihui/tinytex')
tinytex::install_tinytex(TRUE, repository = 'http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet')
```

**Comment by ferristale** [comment]
Thanks for your support. 
Here are some further details:
I use a CSTNET network, and the program chose `ftp.math.pur­due.edu` automatically for me.
Totally it took me about 20 minutes to install.
