### ISSUE TITLE
A suggestion when upgrading TeX Live annual update

### ISSUE THREAD

**Issue by uninyhart** [yihui/tinytex#140]
仅仅是个建议。

年度更新需要重装宏包。

可以在把旧版本删除之前，先把装过的宏包列表列出来

```sh
tlmgr list --only-installed
```

然后，在安装完新版本后，再把这些宏包全部装上。

或者说，这相当于维护一份常用宏包列表。

也许这个建议（给非 R 用户）可以在用户手册中加一下？

---

当然如果是 R 用户，这些是自动搞定的……

**Comment by yihui** [comment]
好建议，不过它早已经在 FAQ 11 中了: https://yihui.name/tinytex/faq/ 我可能需要在首页提一下。谢谢！
