### ISSUE TITLE
is it possible to specify the mirror during  tinytex installation and config ?

### ISSUE THREAD

**Issue by hammao** [yihui/tinytex#149]
Below is the error i got repeatedly, it appears installation from mirrors hosted in some countries are not allowed in the country i live. 

> Error in setwd(dir) : character argument expected
> In addition: Warning messages:
> 1: In download.file(url, output, ..., method = method) :
>   cannot open URL 'http://ctan.yazd.ac.ir/systems/texlive/tlnet/install-tl.zip': HTTP status was '403 Forbidden'
> 2: In download.file(url, output, ..., method = method) :
>   InternetOpenUrl failed: 'The operation timed out'
> 3: In download.file(url, output, ..., method = method) :
>   cannot open URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip': HTTP status was '403 Forbidden'
> 4: In unzip("install-tl.zip") : error 1 in extracting from zip file
> Please quit and reopen your R session and IDE (if you are using one, such as RStudio or Emacs) and check if tinytex:::is_tinytex() is TRUE.

**Comment by hammao** [comment]
This post  on stackoverflow solved my problem [how to install tinytex from local zip file in R](https://stackoverflow.com/questions/56770843/how-to-install-tinytex-from-local-zip-file-in-r?noredirect=1&lq=1)

**Comment by yihui** [comment]
Please see the `repository` argument on the help page `?tinytex::install_tinytex` for how to set the CTAN mirror.
