### ISSUE TITLE
how can i use tlmgr directly?

### ISSUE THREAD

**Issue by ferristale** [yihui/tinytex#15]
if I need to run some other command in tlmgr, how can I do that?

**Comment by ferristale** [comment]
I found it in terminal tap of Rstudio, can I use it directly in Linux terminal?

**Comment by Bakaniko** [comment]
I guess you have to use a Rscript command like:

R -e 'getwd()'

so you can call a R command line.

For example to install tinytex:

R -e 'library(tinytex); tinytex::install_tinytex()'




2018-01-19 7:51 GMT+01:00 ferristale <notifications@github.com>:

**Comment by ferristale** [comment]
@Bakaniko Thanks a lot, it's a new skill for me.

**Comment by Bakaniko** [comment]
You're welcome :)

Actually, I had to look into internet to find the right syntax, saw it in
another context, but never used it before today. It is a new skill for me
too :)



2018-01-19 10:18 GMT+01:00 ferristale <notifications@github.com>:

**Comment by yihui** [comment]
Yes, you can either run the command `tlmgr` directly in your terminal (unless you are using a Linux distribution that does not respect `~/bin` in `PATH` by default), or call the R function `tinytex::tlmgr()`, which is basically a command-line wrapper of the system command `tlmgr`.

You can use any other commands in TeX Live if you are familiar with them, such as `kpsewhich`.
