### ISSUE TITLE
How to completely uninstall TinyTeX

### ISSUE THREAD

**Issue by mrzool** [yihui/tinytex#153]
Hello, can you please explain how can I wipe TinyTeX from my system? Which directories do I need to remove? I couldn't find any guide for this on the website.

Thanks.

**Comment by yihui** [comment]
Press <kbd>Ctrl + F</kbd> (or <kbd>Command + F</kbd> on macOS) and search for "uninstall".

**Comment by mrzool** [comment]
That was easy. Thanks!
