### ISSUE TITLE
Include atbegshi package?

### ISSUE THREAD

**Issue by hadley** [yihui/tinytex#163]
I think this is causing github action failures: https://github.com/tidyverse/tidyr/runs/338156252#step:9:94

```R
! LaTeX Error: File `atbegshi.sty' not found.
```

**Comment by hadley** [comment]
To successfully build my package, I need to add:

          tlmgr install atbegshi
          tlmgr install atveryend
          tlmgr install rerunfilecheck

**Comment by yihui** [comment]
Added. Thanks for the report!
