### ISSUE TITLE
Allow overriding path settings or disable path actions

### ISSUE THREAD

**Issue by norbusan** [yihui/tinytex#179]
Hi

currently tinytex installs links to the programs into `~/bin` using `tlmgr path`. I am not overly happy about that and would like to have an option to supress or specify a different directory, something like
```
tinytex::install_tinytex(path = ....)
```
where `path = 'auto'` or undefined uses the defaults, installing into `~/bin` (backward compatibility). If `path = '/some/dir'` is given, the links are installed into this directory, and if `path = 'off'` (or similar) is given, no `tlmgr path` action is carried out, and the user needs to add the `~/.TinyTeX/bin/ARCH/` to the PATH by itself.

Would this be possible?

Reason: I have already several `tlmgr` installed: `/usr/bin/tlmgr` from Debian, `~/tl/2019/bin/ARCH` from TUG TL installation, and `~/.TinyTeX/bin/ARCH`. I want to select the TeX Live to be used on the fly by adjusting the `PATH` accordingly. 

All the best

Norbert

**Comment by yihui** [comment]
Done. I have added an argument `add_path` so you can disable the action via `add_path = FALSE`. Thanks for the suggestion!

**Comment by norbusan** [comment]
Great, thanks a lot!!!
