### ISSUE TITLE
TinyTex License

### ISSUE THREAD

**Issue by dlejay** [yihui/tinytex#201]
The file [DESCRIPTION](https://github.com/yihui/tinytex/blob/master/DESCRIPTION) says

> License: MIT + file LICENSE

but [LICENSE](https://github.com/yihui/tinytex/blob/master/LICENSE) says

> YEAR: 2017-2020
COPYRIGHT HOLDER: Yihui Xie and RStudio, PBC

Is TinyTex open source? If so, maybe LICENSE could be updated so that GitHub recognises it.

**Comment by yihui** [comment]
Too many stories behind this... https://github.com/tidyverse/tidyr/issues/262

Presumably https://github.com/licensee/licensee/pull/129 should make Github able to detect the license of R packages, but it doesn't seem to work...
