### ISSUE TITLE
Cannot properly install TinyTex on Windows - access is denied

### ISSUE THREAD

**Issue by KubaMichalczyk** [yihui/tinytex#208]
I've been trying to install TinyTex from RStudio using `tinytex::install_tinytex()` and bumped into the issue of `Access is denied` at the end of installation. I use corporate laptop with Windows installed, but I'm having a local administrator privilages. From what I noticed it looks like installation was finished, although is not complete. 

`tinytex::tinytex_root()` returns the following directory: `"C:\\Users\\username\\AppData\\Roaming\\TinyTeX"`, but from what I noticed this directory is not set in PATH variable (although I restarted RStudio after installing latex). I also tried to install TinyTex using `tinytex:::install_prebuilt()` but it resulted in `Access is denied` error as well. 

When I'm trying to compile the test.Rmd file I get:

    In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
      'CreateProcess' failed to run 'C:\Users\username~1\AppData\Roaming\TinyTeX\bin\win32\pdflatex.exe -halt-on-error -interaction=batchmode "test.tex"'
    Execution halted

Therefore, I'd like to ask if there is anything what I can do to get TinyTex properly installed? Can I at least navigate to which directory should I have access to finish the installation?

Here's the output of `xfun::session_info('tinytex')`:

    R version 3.6.3 (2020-02-29)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 18362), RStudio 1.2.5042
    
    Random number generation:
     RNG:     Mersenne-Twister 
     Normal:  Inversion 
     Sample:  Rounding 
     
    Locale:
      LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250
      LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    
    
    Package version:
      graphics_3.6.3  grDevices_3.6.3 stats_3.6.3     tinytex_0.22    tools_3.6.3     utils_3.6.3     xfun_0.13

I have previously asked about the issue at [SO](https://stackoverflow.com/questions/61662080/cannot-install-tinytex-on-windows-access-is-denied)

**Comment by yihui** [comment]
I'm afraid I'm unable to help here. I don't know what this error means. Some results from googling:

- https://github.com/rstudio/rstudio/issues/5681
- https://community.rstudio.com/t/failed-to-run-c-pdflatex-exe/49079
- https://community.rstudio.com/t/error-generating-pdf-in-r-markdown/60003

Sorry.
