### ISSUE TITLE
tinytex(::latexmk) won't find any local *.sty files in base/main directory 

### ISSUE THREAD

**Issue by NMarkgraf** [yihui/tinytex#22]
Hi folks,

after upgrading rmarkdown and use tinytex I found a serious bug, I think it is one.

Normally you may have a main directory in which your, lets say, test.Rmd files is. Let us guess you make a pdf (with keep_tex=true) out of it. You also uses a latex style file, name it mystyle.sty which is also in the main directory. You might render it, no problems.

BUT: If you use the latest  rmarkdown and tinytex AND use an output_directory different from the main directory, you got into trouble!

I the old day, a temporary tex and pdf file was build in the main directory and moved after that into the output_directory, everything went well. 
But now, it seems that you build the tex file first in the output_directory and rund latexmk (r something) on it in that directory, which is worse. Because the latex sty-files would not be in the search path of latex any more. 
This is extremely annoying where you use your own beamer theme files (which are .sty files). 

What might help as a quick bugfix is: Add the main directory to TEXINPUTS environment variable of the shell you use before starting any latexmk word. Something like "setenv TEXINPUTS ..:" or appropriate.

There is probably a much better solution, than my workaround... copying all tex and sty files to the output_directory is none!

Yours
Norman

**Comment by yihui** [comment]
It will be great if you could test the development version:

```r
devtools::install_github('yihui/tinytex')
```

**Comment by drabinova** [comment]
Hi folks,
I have the same problem as @NMarkgraf. With `rmarkdown v1.8.` everything works fine. I can use my `.sty` file with different output directory. However this is not possible with `v1.9`. 
I try development version of `tinytex`. Again, with `v1.8` no problem, with `v1.9` I received error from BibTex.

```
This is BibTeX, Version 0.99d (MiKTeX 2.9.6300 64-bit)
The top-level auxiliary file: analysis.aux
I found no \citation commands---while reading file analysis.aux
I found no \bibdata command---while reading file analysis.aux
I found no \bibstyle command---while reading file analysis.aux
(There were 3 error messages)
Error: Failed to build the bibliography via bibtex
In addition: Warning messages:
1: running command '"bibtex" "analysis.aux"' had status 1 
2: running command '"bibtex" "analysis.aux"' had status 1 
Execution halted
```

The pdf output is saved in the main directory, even if it is specified otherwise. The tex file is in correct directory. However, pdf is not properly knitted.

My `sessionInfo()`:

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Czech_Czechia.1250  LC_CTYPE=Czech_Czechia.1250    LC_MONETARY=Czech_Czechia.1250
[4] LC_NUMERIC=C                   LC_TIME=Czech_Czechia.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  backports_1.1.1 magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6
 [6] tools_3.4.3     yaml_2.1.17     Rcpp_0.12.14    stringi_1.1.6   rmarkdown_1.9  
[11] knitr_1.20      stringr_1.3.0   digest_0.6.12   evaluate_0.10.1
```

**Comment by NMarkgraf** [comment]
Hi folks,

rmarkdown 1.8 & *no* tinytex - worked as expected. 
rmarkdown 1.9 & *no* tinytex - doesn't work at all! (As I told you!)
rmarkdown 1.9 & tinytex 0.3.6 - doesn't work:
```
/usr/local/bin/pandoc +RTS -K512m -RTS Datenerhebung-Statistik.utf8.md --to beamer --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures+raw_tex+header_attributes --output pandoc91f4d09350d.tex --slide-level 2 --highlight-style tango --pdf-engine pdflatex --self-contained --include-in-header header.tex --include-before-body before.tex ./private.yaml -V papersize=A4 -V fontsize=12pt -V lang=de -V linkcolor=blue -V urlcolor=blue -V theme=NPBT -V colortheme=FOM -V outertheme=FOM --filter pandoc-filter/typography.py 
This is BibTeX, Version 0.99d (TeX Live 2017)
The top-level auxiliary file: Datenerhebung-Statistik-Wuppertal-STUDIERENDENVERSION.aux
I found no \citation commands---while reading file Datenerhebung-Statistik-Wuppertal-STUDIERENDENVERSION.aux
I found no \bibdata command---while reading file Datenerhebung-Statistik-Wuppertal-STUDIERENDENVERSION.aux
I found no \bibstyle command---while reading file Datenerhebung-Statistik-Wuppertal-STUDIERENDENVERSION.aux
(There were 3 error messages)
Fehler: Failed to build the bibliography via bibtex
```
And of cause, there ist no bib(a)tex used in this Rmd file... an a closer look at the produced tex file says: no bibliography in it!

Sorry, NON of the bugs are fixed right now!

**Comment by NMarkgraf** [comment]
Here is a short test rmarkdown file with a used included tex file, which will produces the described errors with the BibTeX stuff.

[yihui-test.zip](https://github.com/yihui/tinytex/files/1788347/yihui-test.zip)

**Comment by yihui** [comment]
@drabinova @NMarkgraf Could you restart R, `devtools::install_github("yihui/tinytex")`, and retry?

I have tested it with @NMarkgraf's example, and it worked for me. Please provide `devtools::session_info(c('rmarkdown', 'tinytex'))` if it still does not work for you. Thanks!

**Comment by NMarkgraf** [comment]
My examples worked for me. - And with this fix also the bug/issue at rmarkdown (https://github.com/rstudio/rmarkdown/issues/1274) seems to disappear. - Thanks! Great work!

**Comment by yihui** [comment]
Perfect. Thanks a lot for the bug report as well as the reproducible example!

**Comment by drabinova** [comment]
Everything work perfectly! Thank you for your fix @yihui!

**Comment by drabinova** [comment]
Unfortunately, I have to take back what I've written previously. I'm not able to render PDF with our package `ShinyItemAnalysis`. 

The newest version of `ShinyItemAnalysis` is available on CRAN and on https://github.com/patriciamar/ShinyItemAnalysis 
It can be run with `startShinyItemAnalysis()` function. Reports are generated on Reports page, default setting can be used.

With `rmarkdown 1.8` it works fine. With `rmarkdown 1.9` and your fix I get
```
Stack trace (innermost first):
    58: show_latex_error
    57: on_error
    56: system2_quiet
    55: run_engine
    54: latexmk_emu
    53: tinytex::latexmk
    52: latexmk
    51: rmarkdown::render
    50: download$func [C:\Users\Adisa\Documents\GitHub\ShinyItemAnalysis\inst\shiny-examples\ShinyItemAnalysis/server.R#886]
     1: shiny::runApp
```
Report is generated but cannot be knitted and download.

I do not really see where is the problem and I would appreciate any help.

My session info:
```
Session info -------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  Czech_Czechia.1250          
 tz       Europe/Prague               
 date     2018-03-08                  

Packages -----------------------------------------------------------------------------------------
 package   * version date       source                        
 backports   1.1.1   2017-09-25 CRAN (R 3.4.1)                
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)                
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)                
 glue        1.2.0   2017-10-29 CRAN (R 3.4.2)                
 graphics  * 3.4.3   2017-12-06 local                         
 grDevices * 3.4.3   2017-12-06 local                         
 highr       0.6     2016-05-09 CRAN (R 3.4.0)                
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.1)                
 knitr     * 1.20    2018-02-20 CRAN (R 3.4.3)                
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                
 markdown    0.8     2017-04-20 CRAN (R 3.4.0)                
 methods   * 3.4.3   2017-12-06 local                         
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                
 Rcpp        0.12.14 2017-11-23 CRAN (R 3.4.3)                
 rmarkdown * 1.9     2018-03-01 CRAN (R 3.4.3)                
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.3)                
 stats     * 3.4.3   2017-12-06 local                         
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)                
 stringr   * 1.3.0   2018-02-19 CRAN (R 3.4.3)                
 tinytex     0.3.7   2018-03-08 Github (yihui/tinytex@da0de95)
 tools       3.4.3   2017-12-06 local                         
 utils     * 3.4.3   2017-12-06 local                         
 yaml        2.1.17  2018-02-27 CRAN (R 3.4.3)
```

**Comment by yihui** [comment]
@drabinova Is that the full error message you got in the console? If not, please let me know the full error message. You can also insert a code chunk with `options(tinytex.verbose = TRUE)` in your Rmd document, and see if there are more error messages when you generate the report.

**Comment by drabinova** [comment]
I've restarted my PC and now it works! Report is now (correctly) generated with following warning:
```
Warning: running command '"pdflatex" -halt-on-error -interaction=batchmode 
"~\AppData\Local\Temp\Rtmp6Bkpm7\file1e94741833c9.tex"' had status 1
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6300 64-bit)
entering extended mode
```
With `options(tinytex.verbose = TRUE)` there is no additional error message.

Thank you again for your fix.
