### ISSUE TITLE
Make possible installation of other packages inside installation script

### ISSUE THREAD

**Issue by edusantana** [yihui/tinytex#224]
I have a project that after tinytex installation my [users need to install other packages required by my project](https://github.com/abntex/limarka/blob/master/bin/instaladores/tinytex_install.sh#L8-L27). I would like to have a txt file with extras packages to be installed to speed up entire installation:

- If we have `pkgs-extra.txt` inside current directory during installation then it would be used to be installed with [pkgs-custom.txt](https://github.com/yihui/tinytex/blob/7d5fa2611f031b432d380114b54e718b1b378b33/tools/install-unx.sh#L20)

**Comment by edusantana** [comment]
I would change this line:

```bash
$TEXDIR/bin/*/tlmgr install $(download https://yihui.org/gh/tinytex/tools/pkgs-custom.txt | tr '\n' ' ')
```
to

```bash
$TEXDIR/bin/*/tlmgr install $(download https://yihui.org/gh/tinytex/tools/pkgs-custom.txt | (if [[ -f "pkgs-extra.txt" ]]; then (cat - pkgs-extra.txt); else (cat -); fi) | tr '\n' ' ')
```

**Comment by cderv** [comment]
I believe you can do that using the installation inside R with `tinytex::install_tinytex` and its `extra_packages` argument. 

Is this something you tried already or you are required to use bash ? (you can also use `Rscript -e` to run R code from bash script)

**Comment by yihui** [comment]
I feel this task is simple enough so I tend to let users who need extra packages do it by themselves:

```
tlmgr install $(cat pkgs-extra.txt | tr '\n' ' ')
```

If I were to support this "officially", I'd need to document it and users will learn one more thing that they may or may not really need (i.e., the special file `pkgs-extra.txt`). If you were to do it by yourself, it'd be only one extra line of code.

Thanks for your understanding!
