### ISSUE TITLE
TinyTeX folder increases in size every time tlmgr itself is being updated

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [yihui/tinytex#226]
I noticed something that I believe constitutes a bug: everytime I update tlmgr - irrespective of whether via `tinytex::tlmgr_update()` or `tlmgr update --self` in a terminal - the TinyTeX folder increases in size. Specifically, an additional file of size 16mb, named something like `texlive.tlpdb.1fe7a99f26b3efab0a2a...`, is added to `~/.TinyTeX/tlpkg`.

By now, my TinyTeX folder looks like this:
```
~/.TinyTeX$ du -h --max-depth=1
116K	./texmf-local
165M	./texmf-dist
20M	./texmf-var
8,0K	./texmf-config
45M	./bin
346M	./tlpkg
575M	.
```
I suppose this is unintended, and these files should be deleted automatically at some point?

Here's the obligatory session info:
```
> xfun::session_info('tinytex')
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS, RStudio 1.3.959

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
  LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

Package version:
  graphics_4.0.2  grDevices_4.0.2 stats_4.0.2     tinytex_0.24    tools_4.0.2    
  utils_4.0.2     xfun_0.15
```
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
Good observation. I also noticed these files long time ago. I just checked the documentation and it is by design: https://tug.org/texlive/doc/tlmgr.html#update-option...-pkg

> <p><code>tlmgr</code> saves a copy of the <code>texlive.tlpdb</code> file used for an update with a suffix representing the repository url, as in <code>tlpkg/texlive.tlpdb.</code><i>long-hash-string</i>. These can be useful for fallback information, but if you don't like them accumulating (e.g., <code>mirror.ctan.org</code> resolves to many different hosts, each resulting in a possibly different hash), it's harmless to delete them.</p>

Unfortunately `tlmgr` didn't provide an option to clean up these files, so I have to do it on my side. Please see 3d45502.
