### ISSUE TITLE
2 warnings after tinytex::install_tinytex()`

### ISSUE THREAD

**Issue by yuliaUU** [yihui/tinytex#232]
I suddenly started to have issues with tinytext:
`
tinytex::install_tinytex()`
```
Please quit and reopen your R session and IDE (if you are using one, such as RStudio or Emacs) and check if tinytex:::is_tinytex() is TRUE.
Warning messages:
1: Detected an existing LaTeX distribution (e.g., pdftex is at C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdftex.exe). You are recommended to uninstall it, although TinyTeX should work well alongside another LaTeX distribution if a LaTeX document is compiled through tinytex::latexmk(). 
2: In file.remove("TinyTeX/install-tl.log") :
  cannot remove file 'TinyTeX/install-tl.log', reason 'No such file or directory'

I am not exactly sure how to proceed here
```

**Comment by yuliaUU** [comment]
the full output: ```
MiKTeX-pdfTeX 4.0.1 (MiKTeX 20.6.29)
Â© 1982 D. E. Knuth, Â© 1996-2020 HÃ n Tháº¿ ThÃ nh
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.61.1; using libcurl/7.61.1 WinSSL
compiled with expat version 2.2.6; using expat_2.2.6
compiled with jpeg version 9.3
compiled with liblzma version 50020042; using 50020042
compiled with libpng version 1.6.37; using 1.6.37
compiled with libressl version LibreSSL 2.8.2; using LibreSSL 2.8.2
compiled with MiKTeX Application Framework version 4.0; using 4.0
compiled with MiKTeX Core version 4.0; using 4.0
compiled with MiKTeX Archive Extractor version 4.0; using 4.0
compiled with MiKTeX Package Manager version 4.0; using 4.0
compiled with poppler version 0.60.1
compiled with uriparser version 0.9.2
compiled with zlib version 1.2.11; using 1.2.11
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
Content length 329 bytes
downloaded 23.1 MB

trying URL 'https://yihui.org/gh/tinytex/tools/pkgs-custom.txt'
Content length 57 bytes
downloaded 547 bytes

trying URL 'https://yihui.org/gh/tinytex/tools/tinytex.profile'
Content length 57 bytes
downloaded 183 bytes

Starting to install TinyTeX to C:\Users\egoro\AppData\Roaming/TinyTeX. It will take a few minutes.
Use of uninitialized value $ver in scalar chomp at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLWinGoo.pm line 205.
Use of uninitialized value $ver in substitution (s///) at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLWinGoo.pm line 206.
Use of uninitialized value $ver in substitution (s///) at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLWinGoo.pm line 206.
Automated TeX Live installation using profile: ../tinytex.profile
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2635.
Setting up tar with C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/installer/tar.exe as C:\Users\egoro\AppData\Local\Temp\RtmpCurYat\install-tl-20200725\tlpkg\installer\tar.exe didn't work
GNU tar 1.11.8 + 2.2(WIN32)
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2618.
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2618.
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2635.
Setting up curl with C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/installer/curl/curl.exe as C:\Users\egoro\AppData\Local\Temp\RtmpCurYat\install-tl-20200725\tlpkg\installer\curl\curl.exe didn't work
curl 7.66.0 (i386-pc-win32) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.9.0
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI libz
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2618.
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2635.
Setting up wget with C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/installer/wget/wget.exe as C:\Users\egoro\AppData\Local\Temp\RtmpCurYat\install-tl-20200725\tlpkg\installer\wget\wget.exe didn't work
GNU Wget 1.20.1 built on mingw32.

-cares +digest -gpgme +https +ipv6 -iri +large-file -metalink -nls 
-ntlm +opie -psl +ssl/gnutls 

Wgetrc: 
    C:/usr/anothermsys/local/etc/wgetrc (system)
Compile: 
    gcc -std=gnu11 -DHAVE_CONFIG_H 
    -DSYSTEM_WGETRC="/usr/local/etc/wgetrc" 
    -DLOCALEDIR="/usr/local/share/locale" -I. -I../lib -I../lib 
    -I/usr/local/include -DNDEBUG -static 
Link: 
    gcc -std=gnu11 -DNDEBUG -static /usr/local/lib/libgnutls.a -lz 
    -lws2_32 /usr/local/lib/libnettle.a /usr/local/lib/libhogweed.a 
    /usr/local/lib/libgmp.a -lcrypt32 -lz -lws2_32 ftp-opie.o 
    mswindows.o gnutls.o ../lib/libgnu.a -lws2_32 -lws2_32 -lws2_32 
    -lws2_32 /usr/local/lib/libiconv.a -lws2_32 

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2618.
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2618.
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2618.
Can't spawn "cmd.exe": No such file or directory at C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/TeXLive/TLUtils.pm line 2635.
Setting up xz with C:/Users/egoro/AppData/Local/Temp/RtmpCurYat/install-tl-20200725/tlpkg/installer/xz/xz.exe as C:\Users\egoro\AppData\Local\Temp\RtmpCurYat\install-tl-20200725\tlpkg\installer\xz\xz.exe didn't work
xz (XZ Utils) 5.2.4
liblzma 5.2.4
query_ctan_mirror: Programs not set up, trying wget
cannot contact mirror.ctan.org, returning a backbone server!

C:\Users\egoro\AppData\Local\Temp\RtmpCurYat\install-tl-20200725\install-tl: TLPDB::from_file could not initialize from: http://www.ctan.org/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb
C:\Users\egoro\AppData\Local\Temp\RtmpCurYat\install-tl-20200725\install-tl: Maybe the repository setting should be changed.
C:\Users\egoro\AppData\Local\Temp\RtmpCurYat\install-tl-20200725\install-tl: More info: https://tug.org/texlive/acquire.html
Loading http://www.ctan.org/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb
Please quit and reopen your R session and IDE (if you are using one, such as RStudio or Emacs) and check if tinytex:::is_tinytex() is TRUE.
Warning messages:
1: Detected an existing LaTeX distribution (e.g., pdftex is at C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdftex.exe). You are recommended to uninstall it, although TinyTeX should work well alongside another LaTeX distribution if a LaTeX document is compiled through tinytex::latexmk(). 
2: In file.remove("TinyTeX/install-tl.log") :
  cannot remove file 'TinyTeX/install-tl.log', reason 'No such file or directory'
```

**Comment by yuliaUU** [comment]
I aslo looked at logf file, y=this is the tail of the document:
LaTeX Font Info:    Trying to load font information for T1+lmtt on input line 1
94.
(c:/Users/egoro/AppData/Roaming/TinyTeX/texmf-dist/tex/latex/lm/t1lmtt.fd
File: t1lmtt.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    Font shape `T1/lmtt/bx/n' in size <12> not available
(Font)              Font shape `T1/lmtt/b/n' tried instead on input line 195.
[5]

! LaTeX Error: Environment tabu undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.225 \begin{tabu}
                   to \linewidth {>{\raggedright\arraybackslash}p{2cm}>{\rag...
 
Here is how much of TeX's memory you used:
 13102 strings out of 482854
 195976 string characters out of 5954975
 480677 words of memory out of 5000000
 28130 multiletter control sequences out of 15000+600000
 583687 words of font info for 96 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 43i,6n,42p,1114b,364s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!
```

seems as the error starts at ! LaTeX Error: Environment tabu undefined.

**Comment by yihui** [comment]
Could you read and follow [the issue guide](new) exactly to provide all the required information? As requested, please do not ignore or delete the issue guide in your post, otherwise it is usually hard for us to help you. Thanks!
