### ISSUE TITLE
Usage of relative paths and /inst instead of download and /tools?

### ISSUE THREAD

**Issue by Thell** [yihui/tinytex#234]
Hi yihui! TinyTex rocks! Thank you.

I do have a question though... did the use of hardcoded URLs come from a design decision or its what you use and it works so it stays?

It's the only part of my current build pipeline that I can't do locally from a `master.tar.gz` or release bundle `tinytex.tar.gz` without patching; which is totally fine, no problem with doing that, I am just wondering if there was a reason that the install scripts in `/tools` wasn't included with the R package itself to use relative paths?

My guess is that its because the install of TinyTex is actually targeted at more than just R and the scripts serve as working solutions _and_ examples for customizing but I thought I'd ask.

If there is room for a feature request to _not_ use hardcoded downloads when the package is already present then this could be tagged as a feature request I guess. 🙂 

Thanks again for being awesome!

**Comment by yihui** [comment]
The main reason is that I can't make new releases to CRAN at any time or frequency (CRAN recommends no more than 6 releases in 6 months), so if any problem occurs, I wouldn't be able to make corrections immediately on my side if I put the scripts in `inst/` and retrieve them via `system.file()` in R. Without this problem, I'd be happy to put the scripts anywhere in the package. Thanks for your feedback!

**Comment by Thell** [comment]
Thanks, that makes sense. I'm sure the setup will stabilize. The binary bundle goes a long way to helping with a quick and painless setup, it is also straight forward on custom install paths. So 👍 on that! So far it is working well and the package selection in the binary bundle handles getting the standard things built. Definitely an option that deserves some front-page exposure, imo.

This is how I'm using it:
```bash
# TinyTex install prep, holds TexLive installs with a 2020-01 stub.
cd /tmp
equivs-build ~/texlive-local.txt
dpkg -i ./texlive-local_*.deb

### TinyTeX
# Utilize pre-built TinyTex bundle
CTAN_REPO=http://localhost:8081/repository/texlive/tlnet
TINYTEX_HOME=${XDG_LIB_HOME}/TinyTeX
mkdir -p ${TINYTEX_HOME}
mkdir -p ${XDG_DATA_HOME}/info
mkdir -p ${XDG_DATA_HOME}/man
wget -O TinyTeX.tar.gz $(nexus_tinytex_latest)
tar zxf TinyTeX.tar.gz -C ${TINYTEX_HOME} --strip=1

cd ${TINYTEX_HOME}/bin/*/
./tlmgr repository add ${CTAN_REPO} nexus_ctan
./tlmgr option repository nexus_ctan
./tlmgr option sys_bin ${XDG_BIN_DIR}
./tlmgr option sys_info ${XDG_DATA_HOME}/info
./tlmgr option sys_man ${XDG_DATA_HOME}/man
./tlmgr path add
```
* The `nexus` stuff is for nexus repository proxy.

**Comment by yihui** [comment]
Great! Thanks for your understanding!
