### ISSUE TITLE
Which license is TinyTex distributed under?

### ISSUE THREAD

**Issue by thejinx0r** [yihui/tinytex#241]
Hi,

#201 stated that TinyTex is open source, but it did not resolve which license it is distributed as. 
Can you confirm which license you are distributing tinytex under?

To add to this confusion, on the website here https://yihui.org/tinytex/:
the license points to Creative Commons 4.0. Can you comment on this? I assume it's just for the website design and not the code itself, but it is not clear.

Eric

**Comment by naveen521kk** [comment]
Refer https://github.com/yihui/tinytex/pull/239#issuecomment-691605464
I asked the same question and I looks like rpackage need to it and I really don't understand.

**Comment by yihui** [comment]
> Can you confirm which license you are distributing tinytex under?

GPL-2 ([like the Debian package texlive](https://metadata.ftp-master.debian.org/changelogs//main/t/texlive-base/texlive-base_2016.20170123-5_copyright)). I just added a sentence in README. Thanks!

> To add to this confusion, on the website here https://yihui.org/tinytex/:
> the license points to Creative Commons 4.0. Can you comment on this? I assume it's just for the website design and not the code itself, but it is not clear.

Yes, the CC license applies to the web page.
