### ISSUE TITLE
Error in getMetricsFromLatex for 12-tikz.Rmd ---closed

### ISSUE THREAD

**Issue by jimrpy** [yihui/tinytex#247]
Dear Yihui,

An error raises when I run your code in 12-tikz.Rmd from https://bit.ly/dahshu-down. 

processing file: 12-tikz.Rmd
List of 1
 $ include: logi FALSE

  |...................................                                   |  50%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-1
  |..........................................................            |  83%
  ordinary text without R code

  |......................................................................| 100%
label: dnorm (with options) 
List of 3
 $ dev        : chr "tikz"
 $ fig.process: symbol pdf2png
 $ cache      : logi TRUE

Quitting from lines 31-36 (12-tikz.Rmd) 
Error in getMetricsFromLatex(TeXMetrics, verbose = verbose) : 
TeX was unable to calculate metrics for:

	m

Run the following commands for diagnosis:

	tikzTest()
	tikzTest("m")

Common reasons for failure include:
  * The string contains a character which is special to LaTeX unless
    escaped properly, such as % or $.
  * The string makes use of LaTeX commands provided by a package and
    the tikzDevice was not told to load the package.

The TeX and log files used for the calculation can help diagnose the
problem. If these files are missing, rerun the plot and make sure to
keep the R session open.
TeX file: tikzStringWidthCalc.tex
Log file: tikzStringWidthCalc.log
Calls: <Anonymous> ... Axis.default -> axis -> <Anonymous> -> getMetricsFromLatex
Execution halted

sessioninfo::session_info()
─ Session info ──────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Asia/Shanghai               
 date     2020-09-28                  

─ Packages ──────────────────────────────────────────────────────
 package     * version date       lib
 assertthat    0.2.1   2019-03-21 [1]
 cli           2.0.2   2020-02-28 [1]
 crayon        1.3.4   2017-09-16 [1]
 digest        0.6.25  2020-02-23 [1]
 evaluate      0.14    2019-05-28 [1]
 fansi         0.4.1   2020-01-08 [1]
 glue          1.4.2   2020-08-27 [1]
 htmltools     0.5.0   2020-06-16 [1]
 knitr         1.30    2020-09-22 [1]
 magick        2.4.0   2020-06-23 [1]
 magrittr      1.5     2014-11-22 [1]
 Rcpp          1.0.5   2020-07-06 [1]
 rlang         0.4.7   2020-07-09 [1]
 rmarkdown     2.3.9   2020-09-28 [1]
 rstudioapi    0.11    2020-02-07 [1]
 sessioninfo   1.1.1   2018-11-05 [1]
 withr         2.3.0   2020-09-22 [1]
 xfun          0.17    2020-09-09 [1]
 yaml          2.2.1   2020-02-01 [1]

-----
>  Sys.which('pdflatex')
                 pdflatex 
"/usr/local/bin/pdflatex" 
> system("kpsewhich article.cls")
/Users/james/Library/TinyTeX/texmf-dist/tex/latex/base/article.cls

**Comment by jimrpy** [comment]
Here are some warning messages when run `tinytex::install_tinytex()`
tlmgr conf auxtrees add '/Library/Frameworks/R.framework/Resources/share/texmf'
Warning messages:
1: In file(con, "r") :
  cannot open file '/texmf-dist/web2c/fmtutil.cnf': No such file or directory
2: In download.file(url, output, ..., method = method) :
  URL 'https://yihui.org/tinytex/TinyTeX-1.tgz': status was 'SSL connect error'

**Comment by yihui** [comment]
1. To use the `tikz` device, you need more LaTeX packages: https://bookdown.org/yihui/rmarkdown-cookbook/graphical-device.html

2. The warnings can be safely ignored. I have fixed the first warning via 825222de1075204ec05e758cf0bea44accc857d7 (you need to `remotes::install_github('yihui/tinytex')`).

**Comment by jimrpy** [comment]
Thanks.  All done!!

Checked by `tikzDevice::tikzTest()`, the result is **LaTeX Error: File `grfext.sty' not found.**

After installed the [missing package](https://bookdown.org/yihui/rmarkdown-cookbook/install-latex.html) with `tinytex::tlmgr_install(c('grfext'))`, it works!!!

**Comment by yihui** [comment]
Good to know! `tinytex::parse_install(files = 'grfext.sty')` is a more robust way because the `.sty` filename is not always the same as the LaTeX package name: https://bookdown.org/yihui/rmarkdown-cookbook/install-latex-pkgs.html
