### ISSUE TITLE
Add mention of the tex distribution used on error message. 

### ISSUE THREAD

**Issue by cderv** [yihui/tinytex#263]
Currently we print some information to help on error 
https://github.com/yihui/tinytex/blob/5199a89d0d7c01b166eb7dced1b117c67b569774/R/latex.R#L326-L346

Often we need to asked which distribution is used when people ask for help on QA site. 

One idea would be to add information regarding the TeX distribution used in the error message printed in R, specifically if TinyTeX is used or not. 

Otherwise to help debug we could provide a help function like `tinytex::latex_sitrep()` or `tinytex::sessioninfo()` (but not good to use an existing name) that would help get some important information from the user when they ask for or open their bug. 

What do you think ?

**Comment by yihui** [comment]
I think these are great ideas! Adding a `tinytex:::xfun_session_info` to take advantage of `xfun::session_info()` may also be useful.

**Comment by cderv** [comment]
Great I'll look into that then.
