### ISSUE TITLE
What about exported is_tinytex and check_installed ? 

### ISSUE THREAD

**Issue by cderv** [yihui/tinytex#269]
We advice to use them : https://github.com/rstudio/rticles/pull/364#discussion_r561036426

and I often use `"revtex4-1" %in% tinytex::tl_pkgs()` to check what I could do with `tinytex:::check_installed("revtex4-1")`

So why not ?

**Comment by yihui** [comment]
I was just too lazy to document them :) For `is_tinytex()`, it is also a little hackish:

```r
any(grepl(
    '\\W[.]?TinyTeX\\W',
    readLines(file.path(root, 'texmf-dist/web2c/fmtutil.cnf'), n = 1)
))
```

I guess it should work for 99.999% of cases, though.

Anyway, I'll export and document them.

**Comment by cderv** [comment]
I can also do it :) 

I open issue here mainly to share ideas with you, but feel free to say ok, then assign me 😄 
Especially for those were lazyness win 😉 

BTW `check_installed` is the most useful.

**Comment by yihui** [comment]
It's only a 10-min task, so I'm happy to do it. I have more boring tasks that I feel definitely too lazy to do. For example, I have been hoping to change the test syntax from `assert(cond1, cond2)` to `assert({ (cond1); (cond2) })` in all packages. You may start with **knitr**: https://github.com/yihui/knitr/tree/master/tests/testit

**Comment by cderv** [comment]
Ok ! I can do that on the long run. :)

**Comment by yihui** [comment]
When you feel tired, you may do that, since it doesn't require much brain power :)

The two functions have been documented and exported now.

**Comment by cderv** [comment]
I did that then in **rticles** https://github.com/rstudio/rticles/commit/90795a4c99a5e45361d3a520532ab6cc3f63c170

Is it ok ?

**Comment by yihui** [comment]
Yes.
