### ISSUE TITLE
Problems installing tinytex on OS X 10.11.6

### ISSUE THREAD

**Issue by stuzog** [yihui/tinytex#27]
Having problem installing tinytex on OS X 10.11.6 on iMac 7,1 in RStudio 1.1.414 after first installing the package:

```
> tinytex::install_tinytex()
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   141  100   141    0     0    134      0  0:00:01  0:00:01 --:--:--   135
install-unx.sh: line 1: syntax error near unexpected token `<'
install-unx.sh: line 1: `<html><body>You are being <a href="https://raw.githubusercontent.com/yihui/tinytex/master/tools/install-unx.sh">redirected</a>.</body></html>'
Error: Failed to install TinyTeX
```

UPDATE: TT installed successfully on a new RStudio project, so it must be something in the existing project that caused this.

**Comment by yihui** [comment]
If this is no longer reproducible, I guess there is nothing I could do. It probably requires a relatively recent version of R. From the error log, `download.file('https://github.com/yihui/tinytex/raw/master/tools/install-unx.sh')` was not able to handle the redirect (to `https://raw.githubusercontent.com/yihui/tinytex/master/tools/install-unx.sh`). The only possible reason I could think of is that you probably changed `options(download.file.method)` (the default method `libcurl` should work well in this case).
