### ISSUE TITLE
install-bin-unix.sh won't download default binary on ubuntu 16

### ISSUE THREAD

**Issue by cderv** [yihui/tinytex#280]
See https://github.com/r-lib/actions/issues/213#issuecomment-779729656 for details

In short: 
* We use `wget` to do the download
* The default url with https://yihui.org/tinytex/ throws a 308 redirect (is this expected ?)
* `wget` version on Ubuntu 16 can't follow this redirect - it works ok on ubuntu 20.04 and 18.04

Ubuntu 16.04 will have no more release but there is still support (https://ubuntu.com/about/release-cycle). 

We may need to improve this script:

* Use curl instead of wget ? 
* Try both method ? 

Or change the redirect stuff by appveyor and only point to Github release, by default pointing to the laster binary. 

Would the latter be possible ? I understand the redirect through your site was necessary for some usage.

But this also could be related to this issue ? https://github.com/rbind/yihui/issues/100
Redirection issue with the tinytex part of the website.

**Comment by cderv** [comment]
From https://github.com/rbind/yihui/issues/100, the change to 308 redirect is indeed introduced by the recent switch to use Vercel for yihui.org

**Comment by yihui** [comment]
I just changed the status code to 301. Thanks for the report!

**Comment by cderv** [comment]
@yihui https://yihui.org/gh/tinytex/tools/install-base.sh is still 308 status code
https://github.com/rbind/yihui/blob/3504745b9f120bf2f7a2393000f8e880dbe5c97e/vercel.json#L48-L51

This could cause issue to those using old wget with source installation. e.g. https://github.com/rstudio/r-docker/issues/66#issuecomment-781672992

I recommended to install the new binary but still I wanted to let you know.

**Comment by yihui** [comment]
I just made the change in the status code for these URLs, too. Thanks!
