### ISSUE TITLE
Copy (and overwrite) on successful compilation, instead of renaming existing file

### ISSUE THREAD

**Issue by vqv** [yihui/tinytex#29]
If the PDF output file already exists, the current behavior of `latexmk_emu()` is to rename the existing file and to move it back if the compilation failed.  

https://github.com/yihui/tinytex/blob/c7d62e178915e56728c7b591f4baa0d0f4874c26/R/latex.R#L135

This causes problems with workflows that use an external PDF viewer that monitor changes to the PDF file.  For example, [Skim](https://skim-app.sourceforge.io) on macOS will retain a pointer to the existing file (which is invariant to the renaming) and not see the newly compiled file. This also prevents the existing file from being removed.

Instead, can the behavior of `latexmk_emu()` be changed so that the output destination is given a temporary name, and then upon successful compilation the result is copied on top of the existing file?

**Comment by yihui** [comment]
Sounds like a good idea!
