### ISSUE TITLE
Installation leaves behind TinyTeX.tar.gz

### ISSUE THREAD

**Issue by jeroen** [yihui/tinytex#294]
After running:

```r
tinytex:::install_prebuilt("TinyTeX")
```

My docker image has a work `~/.TinyTex` installation 👍  but also still contains the 160mb `TinyTeX.tar.gz` file. I think the latter should have been removed?

**Comment by yihui** [comment]
I need to export and document this function. To remove the installer, you need

```r
tinytex:::install_prebuilt("TinyTeX", cache = FALSE)
```

In other words, the downloaded installer is cached by default. However, I just discovered a bug, and `cache = FALSE` wouldn't work as expected. It has been fixed in the dev version. Thanks for the report!

**Comment by jeroen** [comment]
OK thank you for the explanation.
