### ISSUE TITLE
the final step might be something wrong

### ISSUE THREAD

**Issue by donk3yzz** [yihui/tinytex#3]
my computer OS is windows and I met this problem while installing tinytex, I run `tinytex::install_tinytex()`
 twice and the results are same like below
> ...
running mktexlsr ...
done running mktexlsr.
running updmap-sys ...
done running updmap-sys.
regenerating fmtutil.cnf in C:/Users/Administrator/AppData/Local/Temp/RtmpQ3NVWQ/install-tl-20171205/TinyTeX/texmf-dist
running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-error-if-no-format --byengine pdftex ...
done running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-error-if-no-format --byengine pdftex.
running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-error-if-no-format --byengine xetex ...
done running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-error-if-no-format --byengine xetex.
running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-error-if-no-format --byengine luatex ...
done running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-error-if-no-format --byengine luatex.
running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-error-if-no-format --byengine luajittex ...
done running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-error-if-no-format --byengine luajittex.tlmgr.pl:package log updated: C:/Users/Administrator/AppData/Local/Temp/RtmpQ3NVWQ/install-tl-20171205/TinyTeX/texmf-var/web2c/tlmgr.log
Use of uninitialized value in bitwise or (|) at C:\Users\ADMINI~1\AppData\Roaming\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 1429.

then I run `tinytex:::is_tinytex()` and it comes `FALSE`..I have no idea now

**Comment by yihui** [comment]
I think the installation has succeeded. You can restart RStudio or R and check `tinytex:::is_tinytex()`.

**Comment by donk3yzz** [comment]
emmm sorry for replying so slow, yesterday I tried several times all results were `FALSE` but it returns `TRUE` now

**Comment by yihui** [comment]
No need to apologize. The key is that you need to restart R or RStudio. Thanks for testing!
