### ISSUE TITLE
xelatex not found in shiny server

### ISSUE THREAD

**Issue by jeevanyue** [yihui/tinytex#30]
我用rocker/shiny配置了shiny server，并安装了需要的packages。在test.Rmd所在文件夹单独运行下列方式是可以的。
`rmarkdown::render('test.Rmd', output_format = 'pdf_document')`
但是在shiny server的shiny app中运行却提示下列错误，实在查不到是什么原因，不知您是否遇到过，有什么解决办法，谢谢！
```
sh: 1: xelatex: not found
Warning: Error in : Failed to compile test.tex.
Stack trace (innermost first):
    58: show_latex_error
    57: on_error
    56: system2_quiet
    55: run_engine
    54: `latexmk_emu`
    53: tinytex::latexmk
    52: latexmk
    51: rmarkdown::render
    50: download$func
     1: runApp
Error : An error has occurred. Check your logs or contact the app author for clarification.
```
下列是相关系统信息。
`$HOME/bin`已经添加到PATH中。`echo $PATH`是`/root`，`echo $PATH`是`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin`
通过`ls -l ~/bin`也找到了`xelatex -> /root/.TinyTeX/bin/x86_64-linux/xelatex`

**Comment by yihui** [comment]
R 包是最新版吗？

要查错的话，我建议先用不依赖 LaTeX 的输出格式，比如 `html_document`，然后在 Rmd 里面输出一下 `Sys.getenv('PATH')` 的信息。

**Comment by jeevanyue** [comment]
@yihui  测试过，输出`html_document `没问题。我先用`rocker/verse`镜像解决这个问题了，不知道是不是将`~/.TinyTeX`移动到`/opt/TinyTeX`就可以解决。先这样吧，我后面再按照`rocker/verse`的配置试一下，非常感谢！
