### ISSUE TITLE
Feature request: Add output directory option to latexmk_emu() and global option to use a temporary directory for output

### ISSUE THREAD

**Issue by vqv** [yihui/tinytex#32]
Two feature requests here:

1.  Add an option to `latexmk_emu()` to specify an output directory.  This is analogous to the `-output-directory` option of `latexmk.pl`.
2. Add a global option to force `latexmk_emu()` to use a temporary directory (via `tempdir()`) for output.

I keep much of my work in a Dropbox, so it would be nice if building didn't happen in-place, as that creates a bunch of temporary files that trigger unnecessary syncing with Dropbox.  When using `latexmk.pl` I am able to specify an temporary directory as an output directory.

**Comment by yihui** [comment]
Install the dev version and set

```r
options(tinytex.output_dir = tempdir(), tinytex.engine_args = shQuote(paste0('--output-directory=', tempdir())))
```

then the PDF should be generated in the temp dir.

#33 should be the ideal implementation, but it is too involved in my eyes, and I don't like it. The implementation in the master branch is hackish, but it is safer, and I guess you are probably the only person who wants this feature, so I'll just let you use the hack :)

**Comment by vqv** [comment]
Just tried it.  There seems to be a problem with how `rmarkdown::render()` works with this.  I'm getting an error here:

https://github.com/rstudio/rmarkdown/blob/8cfc8783636b37876a6dc929dac2395df080e7ac/R/render.R#L669

because `rmarkdown::render()` is not aware of the output directory setting.  I guess what I really need is a way for the build to happen in a temporary directory, but then have the output file moved to the same location of the source file.

**Comment by yihui** [comment]
Currently your only option is `file.rename(tinytex::latexmk(rmarkdown::render('your.Rmd', 'your.tex')), 'your.pdf')` (with the above options set).

**Comment by yihui** [comment]
Or just pause Dropbox...
