### ISSUE TITLE
! Paragraph ended before \MT@prot@l was complete and the fix

### ISSUE THREAD

**Issue by ugoproto** [yihui/tinytex#347]
Greetings and salutations,

Welcome to a new issue.

On this day, we are facing a little bug when compiling PDF with bookdown (using bookdown::pdf_document2:).
We get a `! Paragraph ended before \MT@prot@l`, and the compilation stops (with RStudio, using tinytex, engine lualatex).

The sudden change happened in the last days. Last week, I was able to compile a PDF without any problem.
Today, the problem appeared.

After searching around, it seems the issue has appeared elsewhere; in the LaTeX community.
On `https://tex.stackexchange.com`, one ticket reported:
https://tex.stackexchange.com/questions/625166/maketitle-has-stopped-working-despite-backing-up-data
The quick fix is in the answers with links to other forums.
I applied the `\usepackage{microtype}`,  `\microtypesetup{nopatch=item}`...
I was able to compile a PDF.

I'll leave it to you to investigate the matter et come up with a long-term solution.
Cheers

**Comment by yihui** [comment]
Thanks for the report! It sounds like the problem will be fixed in the next version of the **microtype** package.

**Comment by cderv** [comment]
Yes the `microtype` package last version is buggy. I had a hard time yesterday on this for another related issue and the fix you are sharing is the one I ended up using https://github.com/rstudio/rticles/commit/4e28efaf44094a5a2aaa7fb940ffe2281debf0bb

Hopefully, next version of `microtype` will solve all of them !

Thanks for the report

**Comment by cderv** [comment]
Following the dev version of microtype it seems it has now been fixed. We just need to wait for next microtype release on CTAN

**Comment by jeanetteclark** [comment]
Does anyone have advice on a workaround to use until the CTAN release? Or insight as to how quickly those releases tend to come out? I'm trying to decide what to do with my build that is affected by this.

**Comment by yihui** [comment]
The repo of the **microtype** package is the better place to ask. This issue has been reported and fixed there: https://github.com/schlcht/microtype/issues/3. I think its author has already published the new version to CTAN, and `tinytex::tlmgr_update()` should update it.

**Comment by jeanetteclark** [comment]
Thank you @yihui, `tlmgr_update` resolved my issue

**Comment by yihui** [comment]
Great. I'll close this issue then. Thanks for the confirmation!
