### ISSUE TITLE
Issue with some unicode not rendering

### ISSUE THREAD

**Issue by philstraforelli** [yihui/tinytex#35]
Hi,

I'm trying to create a PDF file in which I am using some wingding font within my chart, and it's not rendering properly when I'm knitting it. This wasn't an issue until switching from MikTex to tinytex.

    ---
    title: "Untitled"
    output: pdf_document
    ---

    ```{r}
    library(ggplot2)
    ggplot(mtcars, aes(x = mpg, y = hp)) + geom_point(shape = sprintf("\u2714"), size = 3)
    ```

The plot with the code above looks fine when I run the plot in R, but I get the following warning message when I knit it:

> Warning in grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size):
> conversion failure on 'âœ”' in 'mbcsToSbcs': dot substituted for < e2>
> Warning in grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size):
> conversion failure on 'âœ”' in 'mbcsToSbcs': dot substituted for <9c>
> Warning in grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size):
> conversion failure on 'âœ”' in 'mbcsToSbcs': dot substituted for <94>
> Warning in grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size): font
> metrics unknown for Unicode character U+2714

The plot gets rendered, but instead of checkmarks, I get "...".

I assume the issue is just a missing latex package, but I'm not sure which one I need to download to fix it.

EDIT: Please note that I added a space between "<" and "e2>" in the warning message above. Oddly the text disappears without that space.

**Comment by yihui** [comment]
I'm pretty sure this issue has nothing to do with tinytex or MiKTeX. The problem is from R, not LaTeX.

Please see the section "Encoding of multibyte characters" at https://yihui.name/knitr/demo/graphics/

**Comment by philstraforelli** [comment]
Hi Yihui,

Thanks for pointing me in the right direction - Unfortunately, the various solutions proposed there did not work. Should I open an issue in the knitr repo?

**Comment by yihui** [comment]
The default LaTeX engine `pdflatex` is not good at dealing with Unicode characters. You may try `xelatex` instead:

````
---
title: "Untitled"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r dev='cairo_pdf'}
library(ggplot2)
ggplot(mtcars, aes(x = mpg, y = hp)) + geom_point(shape = sprintf("\u2714"), size = 3)
```
````

**Comment by philstraforelli** [comment]
Thank you very much for your help, Yihui. `xelatex` did the trick.
