### ISSUE TITLE
GREAT WORK

### ISSUE THREAD

**Issue by NanoMichael** [yihui/tinytex#359]
非常抱歉在这里打扰你！

我是开源项目 [cLaTeXMath](https://github.com/NanoMichael/cLaTeXMath/tree/openmath) 的作者，这是一个可嵌入到应用程序中的 `LaTeX` 公式排版引擎，就像 `MathJax` 一样。说起来非常搞笑，本来这个项目叫 `cLaTeXMath`，我觉得非常难听，所以计划改名为 `TinyTeX`（见[这里](https://github.com/NanoMichael/cLaTeXMath/discussions/93)），但是我并没有搜索是否已经有项目名为 `TinyTeX`，今天刚好我电脑上的 MacTeX 抽风了，想重装一下，于是搜索了一下是否有精简版，于是就来到了这里 :smile: ，然后”深入“了解了一下您，发现作者也是中国人，于是就用中文写了（主要我英文太差）。想着这么有缘，特地来请赐个名（备选 `fasttex`，但是我觉得太傻了）。

**Comment by yihui** [comment]
没关系的。没有打扰，用中文也没问题。

嗯，我想了一会儿，也没想到什么合适的名字……要不是 ctex 多年前就被占用了，它应该就是最好的名字了。

**Comment by NanoMichael** [comment]
非常感谢你的回复！我们最终决定使用 `MicroTeX` 这个名字，它跟 `TinyTeX` 或者 `MiniTeX` 表达的意思都差不多 :smile: 。另外我安装了 `TinyTeX`，非常好用！感谢你的工作。

**Comment by yihui** [comment]
嗯，这名字听起来不错！

只要我的工作对你有用，就是我最大的荣幸。
