### ISSUE TITLE
When installed as root, other users may not be able to use TinyTeX

### ISSUE THREAD

**Issue by wch** [yihui/tinytex#37]
When installed in `/root/.TinyTeX`, other users will not be able to use the programs when the permissions for `/root` are 700. (I believe this is the default for Ubuntu.)

This can be worked around by running `chmod 755 /root` (as I've done [here](https://github.com/rstudio/shiny-examples/blob/f32b494f8/docker/Dockerfile#L48-L57)), but that's generally not desirable from a security standpoint. It would be helpful if the documentation explained another way to install TinyTeX in a way that all users can use it.

**Comment by yihui** [comment]
This is what @cboettig did: https://github.com/rocker-org/rocker-versioned/blob/3d62b38a1310/verse/Dockerfile#L50-L52 Will that be helpful in general?

**Comment by wch** [comment]
It would definitely help to have instructions on how to do a system-wide installation where any user can use it. It would also be nice if the destination directory could be set as an option to the installation script, instead of having to install it first and them move the files, as @cboettig did.

**Comment by yihui** [comment]
Okay, I'll improve the documentation, and think about how to make the installation path configurable. Note that if you have already got R installed, you can use the R function `tinytex::install_tinytex()` to install TinyTeX -- this function has provided a `dir` argument that can be used to specify the installation dir. The shell script doesn't support this at the moment.
