### ISSUE TITLE
! LaTeX Error: Undefined color model `HTML'.

### ISSUE THREAD

**Issue by jfrank94** [yihui/tinytex#370]
I decided to post this here as it's more pertaining to the tinytex aspect of Rmarkdown. I'm having an issue running the render function via Rmarkdown on a VM, as I'm contributing to a project that requires converting an Rmd file to PDF to happen outside of RStudio. However, I'm running into this error after the entire Rmd file is processed, and I haven't found a viable solution yet. I've tried to re-install tinytex, re-installing the Rmarkdown library, added this piece of code to the Rmd file from another [solution](https://github.com/readthedocs/readthedocs.org/issues/2127#issuecomment-216505432): 

```
\IfFileExists{xcolor.sty}{
    \RequirePackage{xcolor}
}{
    \RequirePackage{color}
}
```

But nothing has worked. The Rmd file renders/converts to PDF fine on RStudio, so it probably has nothing to do with the code and sourced R codes in the file themselves. If there are any other solutions, I'm all ears and thank you in advance.

**Comment by yihui** [comment]
It will be great if you could read and follow [the issue guide](new) to provide the required information (especially a minimal reproducible example), otherwise it is usually hard for us to help you. Thanks!

**Comment by jfrank94** [comment]
@yihui Thanks for the prompt response. I can't show much right now, as it is a project that has eventual proprietary means. However, I can show you a snippet of the code where the error is still reproducible. There is a sourced R file, but again, the entire Rmd file renders/knits fine on RStudio, and the sourced R file has zero programmatic/syntax errors. 

```
---
title: "PRS Report"
output:
  pdf_document: 
    latex_engine: xelatex 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## PRS Profile

PRS ID:

PRS Date:

PRS Director:

### Base Dataset

```{r warning=FALSE}
library(gwasrapidd)
gwas_study <- get_studies(study_id = 'GCST004988')
gwas_study_id <- gwas_study@studies$study_id
gwas_study_link <- paste0('https://www.ebi.ac.uk/gwas/studies/', gwas_study_id)
gwas_study_sample_size <- gwas_study@studies$initial_sample_size
gwas_study_title <- gwas_study@publications$title
gwas_study_pumed_id <- paste0('https://pubmed.ncbi.nlm.nih.gov/'  ,gwas_study@publications$pubmed_id)
gwas_study_publications_date <- gwas_study@publications$publication_date

```

**Study Accession:** `r gwas_study_id`

**GWAS Link:** `r gwas_study_link`

**Discovery Sample Size:** `r gwas_study_sample_size`

**Publication Title:** `r gwas_study_title`

**PubMed Link:** `r gwas_study_pumed_id`

**Publication date:** `r gwas_study_publications_date`

### Target Dataset

**Source:**

**Ancestry**

**Patients' Demography:**

```{r message=FALSE, file = 'table_generator_profile.R'}

```



This is also the code I'm using in order to convert it into a PDF: 

```
library(rmarkdown)
render("3-PRS_Report/PRS_Report.rmd", pdf_document(latex_engine = "xelatex"))
```

I hope this helps.

**Comment by yihui** [comment]
> I can't show much right now, as it is a project that has eventual proprietary means.

That's totally understandable, and also exactly why we ask for a "minimal" reproducible example. A minimal example means you keep deleting irrelevant parts of the example until the problem no longer occurs. Usually we don't really need the full original example.

**Comment by jfrank94** [comment]
@yihui Are there any updates on your end?

**Comment by yihui** [comment]
I've still been waiting for your minimal self-contained reproducible example. As I said in my first reply, it's hard to help without it. The example you gave is not self-contained (what's `table_generator_profile.R`?), and probably not minimal (is the **gwasrapidd** package relevant?).

**Comment by jfrank94** [comment]
@yihui My apologies. I thought the sample posted was good for you to reproduce. I may be able to send over everything to you via e-mail as this might be too much to post. There are other files being used during table generation. Do you have an e-mail I can send this to? I hope this is alright with you.

**Comment by jfrank94** [comment]
@yihui Nevermind didn't realize I can attach files on Github. Here are the rest of the files that you need to reproduce. The table generator and required files are all in this zip file for your convenience. Let me know if you need anything else, and thanks again.  

[files.zip](https://github.com/yihui/tinytex/files/8575604/files.zip)

**Comment by yihui** [comment]
> I'm having an issue running the render function via Rmarkdown on a VM

I'm unable to reproduce your issue on my computer. Both the Knit button in RStudio and calling `rmarkdown::render()` worked fine for me. Do you mean your problem only occurs on the VM? My guess is that your VM doesn't have a proper installation of LaTeX. If you (or the maintainer of the VM) haven't already installed TinyTeX, you may install it via `tinytex::install_tinytex()` in R in the VM.

**Comment by jfrank94** [comment]
@yihui So, I've tried to re-install both tinytex and Rmarkdown earlier to solve this issue, but it still wasn't working. Are there any other solutions?

**Comment by yihui** [comment]
> I've tried to re-install both tinytex

I'm not sure if you meant TinyTeX or **tinytex**. You need to install TinyTeX, the LaTeX distribution. Re-installing the R package **tinytex** won't help.



> The VM that we're using is on Azure

Sorry I don't have an Azure account, but your VM needs a proper LaTeX distribution anyway. TinyTeX may be the easiest one to install and manage. If your VM uses another LaTeX distribution, make sure it is the latest and contains the LaTeX package **xcolor** (TinyTeX contains it by default).

**Comment by jfrank94** [comment]
Yes, I meant TinyTeX, the LaTeX distro. I just tried it once more on Azure and I got the same error. I even tried to download xcolor alongside it ```tinytex::tlmgr_install('xcolor.sty')```, and that didn't work either. Still got the same error as originally.

**Comment by jfrank94** [comment]
I got this as a result: ```tlmgr info xcolor```. Nothing else in the traceback.

**Comment by yihui** [comment]
Then it sounds like you don't really have TinyTeX installed... That's odd, since you said you have installed it. What does `tinytex::tinytex_root()` return?

**Comment by jfrank94** [comment]
For ```tinytex::tinytex_root()``` it's at ```'/home/azureusergpu/.TinyTeX'``` and ```Sys.which('xelatex')``` returns ```xelatex: '/usr/bin/xelatex'```.

**Comment by yihui** [comment]
No need to redirect. 

> For `tinytex::tinytex_root()` it's at `'/home/azureusergpu/.TinyTeX'`

That indicates TinyTeX should be correctly installed. Again, I'm puzzled. It shouldn't matter there is another system-level installation of TeX Live.

What does this return?

```r
(function() {
  tinytex:::tweak_path()
  Sys.which('xelatex')
})()
```

**Comment by jfrank94** [comment]
That function returns ```xelatex: '/home/azureusergpu/.TinyTeX/bin/x86_64-linux/xelatex'```.

**Comment by yihui** [comment]
That's correct. I'm out of ideas now...

**Comment by jfrank94** [comment]
If it helps, I'll post the full error trace just in case you want to do any debugging in the library: 

```
I was unable to find any missing LaTeX packages from the error log PRS_Report.log.

! LaTeX Error: Undefined color model `HTML'.


Error: LaTeX failed to compile PRS_Report.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See PRS_Report.log for more info.
Traceback:

1. render("3-PRS_Report/PRS_Report.rmd", pdf_document(latex_engine = "xelatex"))
2. latexmk(texfile, output_format$pandoc$latex_engine, "--biblatex" %in% 
 .     output_format$pandoc$args)
3. tinytex::latexmk(file, engine, if (biblatex) "biber" else "bibtex")
4. latexmk_emu(file, engine, bib_engine, engine_args, min_times, 
 .     max_times, install_packages, clean)
5. run_engine()
6. system2_quiet(engine, c("-halt-on-error", "-interaction=batchmode", 
 .     engine_args, shQuote(file)), error = {
 .     if (install_packages) 
 .         tlmgr_update(run_fmtutil = FALSE, .quiet = TRUE)
 .     on_error()
 . }, logfile = logfile, fail_rerun = verbose)
7. on_error()
8. show_latex_error(file, logfile)
9. stop(e, " See ", logfile, " for more info.", call. = FALSE)
```

As for any other solutions, are there any other libraries that are similar to yours for rendering outside of RStudio? I believe R markdown uses your TinyTeX code, so it might be a stalemate for now.

**Comment by yihui** [comment]
The only possible way left for me to figure it out is that we have a Zoom chat with screensharing so that I can try to debug this problem directly on your computer. Would that be possible?

**Comment by jfrank94** [comment]
Thanks for offering, but that seems a bit invasive. You can create an [Azure free tier account](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/create-free-services) for the VM and test it there. I believe Azure gives you $200 free credit as well and you can turn it off immediately after testing to preemptively stop any charges.

**Comment by yihui** [comment]
I can definitely create an Azure account, but I wonder what I need to do next. Presumably there are things to set up, which is my main concern (I'll need further instructions on how to create the same environment as yours to reproduce your problem).

**Comment by jfrank94** [comment]
Sure, you can read through the link I sent, but if you need any additional help, I can post more instructions here. The specs that we use aren't probably for the free tier, but I don't think it would matter as this process doesn't need GPUs or much RAM/storage. 

```
System Configuration:
Family: GPU
RAM: 14 GB
Storage: 88 GB
```

The VMs run on Linux by default, but we're using the ```x86_64``` kernel distribution. I'm not sure if that's covered under free tier as well. I'll edit this post for more information, but hopefully, this should help in setting things up.

**Comment by yihui** [comment]
I meant that we would have to install R in the VM, and then

```r
install.packages(c('rmarkdown', 'gwasrapidd'))
tinytex::install_tinytex()
```

Then run `rmarkdown::render()` on your example, right? Is that how we should reproduce your problem? I guess the RStudio IDE is irrelevant here?

If my understanding is correct, I'll ask a colleague who is more familiar with the Microsoft stuff than me to investigate it.

**Comment by jfrank94** [comment]
Yes, that's pretty much what you need, in addition to any of the libraries in the table_generator code that might need downloading. I appreciate your extending to other colleagues to solve this issue. Hopefully, we can come to a solution in the next week or so.

**Comment by yihui** [comment]
@cderv If you have time, could you try to render this Rmd example on your computer? [Archive.zip](https://github.com/yihui/tinytex/files/8587987/Archive.zip) If it works fine, could you try it on Azure with TinyTeX installed? Thanks! (You can ignore all replies above)

**Comment by cderv** [comment]
The document renders fine on Windows 10 for me (installing **gwasrapidd** first as `xfun::pkg_attach2` creates an issue in the rendering though)

<details>
<summary>The unrelevant issue if you want to look into @yihui </summary>

````r
Quitting from lines 23-32 (test.Rmd) 
Error in `invokeRestart()`:
! no 'restart' 'muffleMessage' found
Backtrace:
  1. xfun::pkg_attach2("gwasrapidd")
 23. evaluate `<fn>`(`<cllr_mss>`)
 24. base::invokeRestart("muffleMessage")
````

Something with catching message it seems (`warning=FALSE` is on the chunk option

</details>

`colortbl` was installed in the process
```
[1/1, ??:??/??:??] install: colortbl [4k]
````

I'll try to see how to set up a Azure environment for testing.

**Comment by yihui** [comment]
> The unrelevant issue if you want to look into @yihui

@cderv I'm unable to reproduce this `xfun::pkg_attach2()` problem. It sounds like something related to the tidyverse error handling setting? Do you have something like that in your `.Rprofile`?

**Comment by cderv** [comment]
Oh I'll look into this hint. Let me check.

**Comment by cderv** [comment]
It was because I had `xfun.install.packages = "pak"` in .Rprofile, so yes this is coming from interaction of using **pak** to install package in Rmarkdown document; Not that important - we know it is not on our side.

**Comment by cderv** [comment]
> Sure, you can read through the link I sent, but if you need any additional help, I can post more instructions here. The specs that we use aren't probably for the free tier, but I don't think it would matter as this process doesn't need GPUs or much RAM/storage.
> 
> ```
> System Configuration:
> Family: GPU
> RAM: 14 GB
> Storage: 88 GB
> ```
> 
> The VMs run on Linux by default, but we're using the `x86_64` kernel distribution. I'm not sure if that's covered under free tier as well. I'll edit this post for more information, but hopefully, this should help in setting things up.

@jfrank94 we have access to a Azure pro account now. We would need exactly your configuration so that we create the right environment to reprocude 

* You said Linux but is it Ubuntu 20.04 or another one ? I don't see the `x86_64` choice, how can I be sure to select this like you ? 
* Regarding your R installation, I don't think you shared session information. Which is the R version ? Newer R 4.2 ? What are the package version installed ? Can we assume you updated to latest CRAN version ? 
* Regarding TinyTeX, did you upgraded recently to use a the most recent 2022 version ? 

With all the information, I can try recreate an environment and reproduce. Without it, it will be hard for us to investigate more this issue unfortunately. 

Thanks !

**Comment by jfrank94** [comment]
@cderv To answer your questions, the version of Ubuntu we're using is ```18.04``` with the architecture being ```x86_64```, the version of R we're using in 4.1.2, so not the latest, and yes, I'm using the most updated version of TinyTeX. It was installed via this function ```tinytex::install_tinytex()```. 

Here's some additional information if it helps (from invoking ```R.version```): 

```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie 
```

**Comment by cderv** [comment]
Ok so I have tested the example from the bundled posted here https://github.com/yihui/tinytex/issues/370#issuecomment-1112854083 by @yihui 

I can't reproduce. 

@jfrank94 which pandoc version do you have installed ? 

```r
rmarkdown::find_pandoc()
```

thanks

**Comment by jfrank94** [comment]
@cderv It's 1.19.2.4

**Comment by cderv** [comment]
Oh it is really old ! Maybe the pandoc template for LaTeX in that version does not work well with recent TeX Live. FYI Pandoc is now at version 2.18

Is this something that can be updated ? 

Also, using Pandoc > 2 is really adviced. 

other thoughts

> For `tinytex::tinytex_root()` it's at `'/home/azureusergpu/.TinyTeX'` and `Sys.which('xelatex')` returns `xelatex: '/usr/bin/xelatex'`.

Also it seems from this answer you gave that you have another installation of TeX Live on your system considering the path of `xelatex`. Is that possible ? 

I wonder if there could be another installation, with some packages installed and this could be clashing.


Also FWIW I find this error you have initially `! LaTeX Error: Undefined color model `HTML'.` in some post here
https://community.rstudio.com/t/highlighting-text-inline-in-rmarkdown-or-bookdown-pdf/35118/5

It seems the format used was not defining some color
https://community.rstudio.com/t/highlighting-text-inline-in-rmarkdown-or-bookdown-pdf/35118/6?u=cderv

So possible LaTeX issue with template and package.

**Comment by cderv** [comment]
Ok I confirm the Pandoc version is the issue. I can reproduce by installing Pandoc from ubuntu `apt-get install pandoc` which is version 1.19.2.4. I know get the same error. 

The solution for this is to update Pandoc or if you can't you need to tweak the Pandoc latex template to fix the LaTeX issue. But the upgrade to a newer pandoc is the best.

**Comment by jfrank94** [comment]
What's the best way to upgrade Pandoc? @cderv

**Comment by cderv** [comment]
Instruction to install Pandoc are on their website : https://pandoc.org/installing.html

What is built into ubuntu is realy not up to date. Getting version from release page is better: https://github.com/jgm/pandoc/releases

Using CLI tool you do do something like this 

````
# install gh for easier download of release assets
sudo apt-get install gh
# download latest bundle (change pattern is needed another one)
gh release download -R jgm/pandoc --pattern '*amd64.deb'
# install 
sudo dpkg -i $(ls pandoc-*.deb)
# remove downloaded bundle
rm $(ls pandoc-*.deb)
````

But you should check the page and install the version want. You can also get a tar.gz to have a portable binary if you don't want system install

**Comment by jfrank94** [comment]
@cderv @yihui Thank you all for your help on this. It finally was able to convert on the VM!
