### ISSUE TITLE
Installation of TinyTeX failed

### ISSUE THREAD

**Issue by arnonl** [yihui/tinytex#38]
Dear developer,

I'm running MacOS High Sierra. When using the tinytex::install_tinytex() command I got the following error:
<img width="740" alt="screen shot 2018-04-30 at 6 13 29 pm" src="https://user-images.githubusercontent.com/12034136/39453850-ec37b5a4-4ca5-11e8-812b-7e0289c38d57.png">

add_link_dir_dir: destination /usr/local/bin not writable, no links from /Users/Arnon/Library/TinyTeX/bin/x86_64-darwin.
tlmgr: An error has occurred. See above messages. Exiting.
add of symlinks had 1 error(s), see messages above.
Error: Failed to install TinyTeX

Can you please explain how to work around it?

Thank you!

**Comment by yihui** [comment]
Duplicate of #24

**Comment by arnonl** [comment]
Worked. Thank you and sorry for the duplication.

**Comment by yihui** [comment]
No worries. I probably should make this an FAQ now.
