### ISSUE TITLE
Missing package. "Remote repository newer than local"

### ISSUE THREAD

**Issue by ronammar** [yihui/tinytex#39]
During knitting, I get the following error:

```
tlmgr search --file --global '/lineno.sty'
tlmgr: Remote repository is newer than local (2017 < 2018)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
! LaTeX Error: File `lineno.sty' not found.
```

Following the *maintenance* instructions on https://yihui.name/tinytex/ I observe the following on the terminal.

```bash
$ tlmgr update --self --all
tlmgr: Remote repository is newer than local (2017 < 2018)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
```

How can TinyTex be updated?

**Comment by ronammar** [comment]
NOTE: resolved by running the following in `R`:
```r
install.packages(c('tinytex', 'rmarkdown'))
tinytex::install_tinytex(force = T)
```

**Comment by yihui** [comment]
You can reinstall TinyTeX as well as the packages you previously installed with:

```r
devtools::install_github('yihui/tinytex')
tinytex::reinstall_tinytex()
```

**Comment by yihui** [comment]
@vargonis Uninstall TinyTeX and reinstall it: https://yihui.name/tinytex/

**Comment by vargonis** [comment]
@yihui OK, thanks. Will I lose the packages that I have already installed?

**Comment by vargonis** [comment]
Thanks, it worked (forced me to learn some elementary command line stuff though). Keep up with the good work, tinytex is great! Something like `reinstall_tinitex()` for non-R users would be very nice. For what it's worth, would like to mention that I also had to re-create, in my /bin directory, a symbolic link to a latexmk command that I found in ~/.TinyTex/bin/x86_64-linux.

**Comment by yihui** [comment]
@vargonis To create symbolic links, you just need to run `tlmgr path add` (this is automatically done for R users). Only LaTeX packages that contain executables require this, such as **latexmk**.

I have added FAQ 13 to address this issue of upgrading TeX Live: https://yihui.name/tinytex/faq/
