### ISSUE TITLE
tlmgr_update() notice (in the doc) might be misplaced

### ISSUE THREAD

**Issue by Bakaniko** [yihui/tinytex#4]
Hi,

Thanks for that package ! Nice to play with !

I used R on ubuntu 16.04 so it was really easy to install.

Output:

```
niko@nicolas-UX32VDA:~$ which pdflatex
/home/niko/bin/pdflatex
niko@nicolas-UX32VDA:~$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
```

so it seems working pretty strait forward 

Then I mixed bash and Rstudio console. I think that your r functions are really useful, and the output is easier to read than in a regular terminal.

The doc [1] says:
> For R users, you can use the corresponding helper functions:
```{r}
library(tinytex)
tlmgr_search('/framed.sty')  # search for framed.sty
tlmgr_install('framed')      # install the framed package
tlmgr_update()               # update everything
```

But you don't have to update after installing a package. Only if you want to update the installed packages (I might be wrong).
So I think it should be in a separate section. What do you think ?

[1]: https://yihui.name/tinytex/

**Comment by yihui** [comment]
I didn't mean you should run `tlmgr_update()` every time. I agree the documentation was confusing, and just revised it. Thanks for the feedback!

**Comment by Bakaniko** [comment]
You are welcome. I have strong interests in that package :)
