### ISSUE TITLE
"Remote repository is newer than local (2017 < 2018)" What's my recourse?

### ISSUE THREAD

**Issue by philstraforelli** [yihui/tinytex#40]
I have a .Rmd file that uses the `fancyhdr.sty` latex package. When I run `tlmgr_search("fancyhdr.sty")` I get the following output:

> tlmgr.pl: Remote repository is newer than local (2017 < 2018)
> Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
> Please see https://tug.org/texlive/upgrade.html for details.

I've looked around the tug.org site, but I didn't spot anything that would help me in this case. Is there a recourse?

**Comment by philstraforelli** [comment]
Saw #39 and that fixed it for me.

**Comment by yihui** [comment]
Good. Actually I have added a `reinstall_tinytex()` function in the dev version of **tinytex**.
