### ISSUE TITLE
[CI] Add appveyor support

### ISSUE THREAD

**Issue by gaocegege** [yihui/tinytex#42]
I think we could add appveyor to run CI on Windows.

**Comment by gaocegege** [comment]
emm Sorry, I misunderstand the meaning of the repository. I am adding CI for Windows for Shanghai Jiao Tong University Thesis template https://github.com/sjtug/SJTUThesis. Then I saw your blog post https://yihui.name/cn/2017/06/lightweight-texlive/ and decided to have a try. But I foound that there is no reference to use the awesome tool, tinytex on AppVeyor. Then I opened the issue.

I thought the CI for this repo will install tinytex and I can refer to the config, then I found that I am wrong. Sorry for that. I am closing the issue 😄

**Comment by yihui** [comment]
Added anyway (to test the TeX Live installer on Windows): https://ci.appveyor.com/project/yihui/tinytex
