### ISSUE TITLE
auto detect and install bib style and hyphen pattern?

### ISSUE THREAD

**Issue by qifei9** [yihui/tinytex#46]
like `\usepackage[bibstyle=trad-abbrv]{biblatex}` needs biblatex-trad https://ctan.org/pkg/biblatex-trad

```
\usepackage{polyglossia}
\setmainlanguage[variant=american]{english}
\setotherlanguage[]{german}
```
needs hyphen-german

**Comment by yihui** [comment]
What would the error message be if the bib style is not installed?

**Comment by qifei9** [comment]
the error message in log is:

```
Package biblatex Info: Trying to load bibliography style 'trad-abbrv'...
Package biblatex Info: ... file 'trad-abbrv.bbx' not found.

! Package biblatex Error: Style 'trad-abbrv' not found.
```

**Comment by yihui** [comment]
Is the error message in the `*.blg` file? If not, what is the filename extension of the log that contains this error message?

**Comment by qifei9** [comment]
The error message is in `*.log`.

**Comment by yihui** [comment]
Okay, the bib style package should be automatically detected now. I don't use `biblatex` myself, so I didn't really test it. Thanks!
