### ISSUE TITLE
dependence of executable file

### ISSUE THREAD

**Issue by qifei9** [yihui/tinytex#48]
The executable programs like biber and xindy could be installed by `tinytex::tlmgr`, however, their dependence may be missing or not match the version installed in the system. For example, xindy needs libncurses. Then, to use xindy, I have to install (part of) texlive from the dist repo.

**Comment by yihui** [comment]
What does biber depend on?

I'm not familiar with xindy or libncurses. Can you provide a minimal .tex example that uses xindy? I wonder what is the error message is if libncurses is not installed. And it sounds like you are using Linux?

Anyway, I probably cannot do anything here from tinytex's side. If you have to use these packages that have external system dependencies, you will have to figure out how to install them by yourself.

**Comment by qifei9** [comment]
I use archlinux. As I seen in arch repo, biber depends on many perl modules https://www.archlinux.org/packages/community/any/biber/ . The biber installed by tinytex does not work for me. 

xindy is used by glossaries/glossaries-extra to sort acronyms. 

```
\usepackage[nomain,acronym,xindy,toc,shortcuts,nopostdot,nogroupskip,nohypertypes={acronym}]{glossaries-extra}
\setabbreviationstyle[acronym]{long-short}
\makeglossaries
\glssetcategoryattribute{acronym}{glossdesc}{firstuc}
\setlength{\glsdescwidth}{0.74\textwidth}
\loadglsentries{acronym}

\begin{document}

\printacronyms[nonumberlist=true,title=Abbreviations,style=long]
...
\acl{ecoli}
...
\end{document}
```
An example like this should work, and you also need an `acronym.tex` file containing `\newacronym{ecoli}{\textit{E. coli}}{\textit{Escherichia coli}}`. The error message is something like 'xindy: cannot find share lib libncurses.so.5'.

By the way, the emulated latexmk cannot correctly compile acronym list, the original latexmk works fine. This may duo to that latexmk needs a special latexmkrc to compile for glossaries/glossaries-extra.

```
add_cus_dep('glo', 'gls', 0, 'makeglossaries');
add_cus_dep('acn', 'acr', 0, 'makeglossaries');

sub makeglossaries {
    my ($base_name, $path) = fileparse( $_[0] );
    pushd $path;
    my $return;
    if ($silent) {
        $return = system "makeglossaries -q $base_name";
    }else{
        $return = system "makeglossaries $base_name";
    }
    popd;
    return $return;
}

push @generated_exts, 'glo', 'gls', 'glg';
push @generated_exts, 'acn', 'acr', 'alg';
$clean_ext .= ' %R.ist %R.xdy %R.run.xml';
```
tinytex aims to save the work and disk space for users. For most users, it is great and works fine. However, when meet these limitations, for example, when using bookdown to write and format a thesis, user has to go back to manually install some packages and/or part of texlive, which involves more work and takes the space again. Would it be possible to use other TeX dist other than tinytex under bookdown/rmarkdown?

**Comment by yihui** [comment]
Yes, of course you can use other LaTeX distributions with the R **tinytex** package: https://yihui.name/tinytex/r/ (see "Other LaTeX distributions").

You can also use the `latexmk` command instead of **tinytex**'s emulation; see `?tinytex::latexmk`.

I guess TinyTeX is probably not a good choice for LaTeX and Linux experts like you.

**Comment by qifei9** [comment]
Many thanks!

Just for ref:
1. Just uninstall `TinyTex` is enough to use other LaTeX dist.
2. To uninstall `TinyTex`:
``` bash
rm -rf ~/.TinyTex
rm -rf ~/bin # or just remove the links in ~/bin
# remove ~/bin from $PATH
```
3. To use `latexmk` instead of tinytex's emulation:
``` R
> options(tinytex.latexmk.emulation = FALSE)
> bookdown::render_book("./index.Rmd","bookdown::pdf_book")
```
