### ISSUE TITLE
Installer does not respect proxy settings 

### ISSUE THREAD

**Issue by cameronbracken** [yihui/tinytex#50]
It seems the installer is not passing the proxy settings from the R environment. I have the `http_proxy` environment variable set, but the texlive installer does not see it. I'm not sure if this is an issue with tinytex or texlive itself. I get to this point in the install process:

```
Starting to install TinyTeX to T:\R\tinytex. It will take a few minutes.
PATH=...
"C:\Users\AppData\Local\Temp\1\Rtmpwrvk7m\install-tl-20180530\install-tl" -profile=../texlive.profile
Automated TeX Live installation using profile: ../texlive.profile
Loading http://mirrors.ibiblio.org/pub/mirrors/CTAN/systems/texlive/tlnet/tlpkg/texlive.tlpdb
First directive needs to be 'name', not <HEAD><TITLE>Authentication Required</TITLE></HEAD> at C:/Users/AppData/Local/Temp/1/Rtmpwrvk7m/install-tl-20180530/tlpkg/TeXLive/TLPOBJ.pm line 104, <$retfh> line 1.
```

You can see the message from my proxy server saying "Authentication Required".

**Comment by yihui** [comment]
I have no idea. From https://www.tug.org/texlive/acquire-netinstall.html

> If you need to download through proxies, use a `~/.wgetrc` file or environment variables with the proxy settings for wget. TeX Live always uses GNU wget to download.

It seems that setting the environment variable `http_proxy` should work, but the texlive installer didn't inherit the environment variable for some reason. I'm afraid you will have to debug this by yourself, since I don't really use Windows or proxy. I'm not sure if `~/.wgetrc` would work.

**Comment by cameronbracken** [comment]
I think something must have changed in TeXLive, since it has worked for me in the past and my settings have not changed. I'll try a few things.

**Comment by yihui** [comment]
Yeah that is likely. I know they have messed around with the downloaders (such as `wget`) in the installer, but I don't know what exactly they did.

**Comment by cameronbracken** [comment]
So it worked to set the following line in ~/.wgetrc (which is C:\Documents\.wgetrc on windows):

```
http_proxy=127.0.0.1:8118
```

**Comment by yihui** [comment]
Perfect. Thanks for posting back!

**Comment by cameronbracken** [comment]
Looks like the install did not actually finish, something strange is going on here. 

```
Welcome to TeX Live!


See ./TinyTeX/index.html for links to documentation.
The TeX Live web site (http://tug.org/texlive/) contains any updates and
corrections. TeX Live is a joint project of the TeX user groups around the
world; please consider supporting it by joining the group best for you. The
list of groups is available on the web at http://tug.org/usergroups.html.

Logfile: ./TinyTeX/install-tl.log
tlmgr.pl: package repository http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/68, ??:??/??:??] install: amscls [32k]
[2/68, 00:00/00:00] install: amsfonts [3542k]
[3/68, 00:05/00:47] install: amsmath [30k]
[4/68, 00:05/00:47] install: babel [140k]
[5/68, 00:09/01:22] install: bibtex.win32 [41k]
[6/68, 00:09/01:21] install: bibtex [15k]
[7/68, 00:10/01:29] install: booktabs [3k]
[8/68, 00:10/01:29] install: caption [32k]
[9/68, 00:10/01:29] install: cm [233k]
[10/68, 00:12/01:40] install: dvipdfmx.win32 [313k]
[11/68, 00:12/01:33] install: dvipdfmx [27k]
[12/68, 00:13/01:40] install: ec [258k]
[13/68, 00:18/02:11] install: etex [12k]
[14/68, 00:18/02:11] install: etoolbox [9k]
[15/68, 00:19/02:18] install: euenc [4k]
[16/68, 00:19/02:18] install: fancyvrb [12k]
[17/68, 00:19/02:18] install: fontspec [26k]
[18/68, 00:19/02:17] install: framed [8k]
[19/68, 00:20/02:24] install: geometry [9k]
[20/68, 00:20/02:24] install: glyphlist [25k]
[21/68, 00:20/02:23] install: graphics [15k]
[22/68, 00:20/02:22] install: graphics-cfg [2k]
[23/68, 00:21/02:29] install: graphics-def [10k]
[24/68, 00:21/02:29] install: gsftopk.win32 [13k]
[25/68, 00:21/02:29] install: gsftopk [4k]
[26/68, 00:21/02:29] install: hyperref [106k]
rename T:/R/tinytex/tlpkg/texlive.tlpdb.tmp to T:/R/tinytex/tlpkg/texlive.tlpdb failed: Permission denied at T:/R/tinytex/tlpkg/TeXLive/TLPDB.pm line 632.
```

**Comment by yihui** [comment]
I have no idea what this error message means. I just tried it on AppVeyor and it seems to work fine: https://ci.appveyor.com/project/yihui/tinytex/build/1.0.26

**Comment by cameronbracken** [comment]
Ugh this is frustrating, can't stand working on windows. Seems this may still be an issue with the proxy. I get the proxy error when trying to re-install, looks like the math.washington.edu mirror seems to partially work but no other mirrors do.

**Comment by cameronbracken** [comment]
That would be amazing, unfortunately I don't have access to any other windows machine. Could that be something that was provided as a "build" on github? I'm sure others would find it useful too.

**Comment by yihui** [comment]
That is entirely possible, but I don't have time for it. Here are some tips for whoever wants to implement it:

1. Use Travis CI to build TinyTeX (TeX Live) on Ubuntu and macOS, and use AppVeyor for Windows.

2. After it is built and installed, zip up the folder, and upload it somewhere. Personally I don't want to provide a permanent download, so I'd use file.io, like what I did in the travis-exitwp repo: https://github.com/yihui/travis-exitwp Then if a user wants to build TinyTeX on the cloud, he/she can fork this repo and set up Travis/AppVeyor. An alternative to file.io is to use the Travis cache or AppVeyor artifacts.

**Comment by yihui** [comment]
Here is a prebuilt version (daily build) of TinyTeX for Windows: https://ci.appveyor.com/api/projects/yihui/tinytex/artifacts/TinyTeX.zip If you `devtools::install_github('yihui/tinytex')`, you can install it via `tinytex:::install_prebuilt()`. Per [FAQ 2](https://yihui.name/tinytex/faq/), I don't really want to publicize this feature, so it is an internal function.

**Comment by cameronbracken** [comment]
Thanks so much! That worked and got around my proxy 😊
