### ISSUE TITLE
"latexmk" is missing in the windows installation

### ISSUE THREAD

**Issue by woodwm** [yihui/tinytex#51]
It takes me a while to figure out how to build Latex file using Atom or VS Code with TinyTex. It seems that in the default installation of windows, "`latexmk`" is missing, thus causes trouble to build the tex file.

`tlmgr install latexmk` solves the problem. It will be good to install this in the default setting as it seems that both Atom and VS code latex package need it to work.

**Comment by yihui** [comment]
TinyTeX only installs pdflatex, xelatex, lualatex, and these packages by default: https://github.com/yihui/tinytex/blob/master/tools/pkgs-custom.txt I didn't know Atom and VS Code use `latexmk` to compile LaTeX documents.

The goal of TinyTeX is to be tiny, and you only install what you need. If you need latexmk, you just install it. If you want a full TeX Live installation, `tlmgr install scheme-full`.

**Comment by woodwm** [comment]
I have tried `[Latex Workshop](https://github.com/James-Yu/LaTeX-Workshop)` for VS Code and `[atom-latex](https://github.com/thomasjo/atom-latex)`for Atom. Both require `latexmk` on Windows and macOS. Actually, it only need to install `latexmk` to build a basic Latex file after installing TinyTex. It is quite a small package (< 500kb) and can save trouble for the users. I think it worth to add to the default package list.

**Comment by yihui** [comment]
Are you sure latexmk does not require a separate installation of Perl?

**Comment by yihui** [comment]
Okay, I have added latexmk to the default list of packages to be included in TinyTeX.
