### ISSUE TITLE
Adding fonts with TinyTeX

### ISSUE THREAD

**Issue by ThierryO** [yihui/tinytex#54]
TinyTeX makes it really easy to distribute TeX style files with a corporate identity as R packages. It only requires `tinytex::tlmgr_conf(c("auxtrees", "add", system.file("local_tex", package = "OurCoolStyle")))` to set it up.

I'm still struggling with fonts. How can we install ttf fonts using TinyTex?

**Comment by Bakaniko** [comment]
Hi,

I use Linux libertine for my memoir.

I had to install on the the system :

sudo  apt install fonts-linuxlibertine

Then in the yaml header of the Rmd file I have this:

header-includes:
  - \usepackage{libertine}

and I have latex-engine set to xelatex

Hopes that will help you,

Nicolas


Le mer. 20 juin 2018 à 11:09, Thierry Onkelinx <notifications@github.com> a
écrit :

**Comment by ThierryO** [comment]
Thanks for the suggestion. That won't for for us because we need to use a font which was created for us. So it is only available as ttf. I'd like to avoid to have it installed as a system font because most users can't do that themselves because they don't have admin rights on their machine.

**Comment by yihui** [comment]
See if `system2('updmap-sys')` can make TeX Live discover your new fonts.
