### ISSUE TITLE
TinyTex installed but is_tinytex() fails

### ISSUE THREAD

**Issue by davibicudo** [yihui/tinytex#58]
The files are correctly placed inside my AppData folder and I can use latex via command line, but is_tinytex() keeps returning false. Reinstalling and Uninstalling also fail (probably for the same reason). I tried also install_tinytex with and without force but nothing seems to solve it. Knitr also won't compile my pdfs. 
Installation folder:
![image](https://user-images.githubusercontent.com/28100741/43086752-67ee2a90-8e9e-11e8-8f46-c2f125514bc6.png)

Maybe the log could show what's going on? ->

TinyTeX installed to C:\Users\Davi Bicudo\AppData\Roaming/TinyTeX
Restart your R session and check if tinytex:::is_tinytex() is TRUE.

Restarting R session...

> tinytex::is_tinytex()
Error: 'is_tinytex' ist kein von 'namespace:tinytex' exportiertes Objekt
> tinytex:::is_tinytex()
[1] FALSE
> tinytex:::is_tinytex()
[1] FALSE
> tinytex::uninstall_tinytex(force=T)
Error in tinytex::uninstall_tinytex(force = T) : 
  TinyTeX does not seem to be installed.
> tinytex::install_tinytex(force=T)
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
Content length 361 bytes
downloaded 18.9 MB

trying URL 'https://github.com/yihui/tinytex/raw/master/tools/pkgs-custom.txt'
Content length 142 bytes
downloaded 275 bytes

trying URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile'
Content length 142 bytes
downloaded 295 bytes

Starting to install TinyTeX to C:\Users\Davi Bicudo\AppData\Roaming/TinyTeX. It will take a few minutes.
PATH=C:\Users\DAVIBI~1\AppData\Local\Temp\RtmpiipPjg\install-tl-20180723\tlpkg\tlperl\bin;C:\Rtools\bin;C:\Program Files\R\R-3.4.3\bin\x64;c:\Rtools\bin;c:\Rtools\mingw_32\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Program Files\ImageMagick-6.9.2-Q16;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Perl64\site\bin;C:\Perl64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319\;C:\Program Files\Perforce;c:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web ages\v1.0\;C:\Tools\nant-0.92\bin;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\GnuWin32\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\PostgreSQL\9.4\bin\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Greenplum\greenplum-clients-4.3.6.2-build-1\bin;C:\Program Files (x86)\Greenplum\greenplum-clients-4.3.6.2-build-1\lib;C:\Program Files (x86)\Greenplum\greenplum-loaders-4.3.6.2-build-1\bin;C:\Program Files (x86)\Greenplum\greenplum-loaders-4.3.6.2-build-1\lib;C:\Program Files\TortoiseGit\bin;C:\Program Files\OpenVPN\bin;C:\Temp\phantomjs-2.1.1-windows\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_162\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_162\bin;C:\Program Files\Mercurial;C:\Users\Davi Bicudo\Via-1.8.1;C:\Program Files (x86)\BaseX\bin;C:\WINDOWS\System32\OpenSSH\;C:\Users\Davi Bicudo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Mercurial
"C:\Users\DAVIBI~1\AppData\Local\Temp\RtmpiipPjg\install-tl-20180723\install-tl" -profile=../texlive.profile
Automated TeX Live installation using profile: ../texlive.profile
cannot contact mirror.ctan.org, returning a backbone server!
Loading http://www.ctan.org/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files\GnuWin32/etc/wgetrc
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files\GnuWin32/etc/wgetrc
C:\Users\DAVIBI~1\AppData\Local\Temp\RtmpiipPjg\install-tl-20180723\install-tl: TLPDB::from_file could not download http://www.ctan.org/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb;
C:\Users\DAVIBI~1\AppData\Local\Temp\RtmpiipPjg\install-tl-20180723\install-tl: maybe the repository setting should be changed.
tlmgr.pl: package repository http://dante.ctan.org/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl install: package already present: amscls
tlmgr.pl install: package already present: amsfonts
tlmgr.pl install: package already present: amsmath
tlmgr.pl install: package already present: bibtex
tlmgr.pl install: package already present: booktabs
tlmgr.pl install: package already present: caption
tlmgr.pl install: package already present: dvipdfmx
tlmgr.pl install: package already present: ec
tlmgr.pl install: package already present: etoolbox
tlmgr.pl install: package already present: fancyvrb
tlmgr.pl install: package already present: fontspec
tlmgr.pl install: package already present: framed
tlmgr.pl install: package already present: geometry
tlmgr.pl install: package already present: graphics
tlmgr.pl install: package already present: graphics-def
tlmgr.pl install: package already present: gsftopk
tlmgr.pl install: package already present: hyperref
tlmgr.pl install: package already present: ifluatex
tlmgr.pl install: package already present: ifxetex
tlmgr.pl install: package already present: latex-bin
tlmgr.pl install: package already present: latexmk
tlmgr.pl install: package already present: lm
tlmgr.pl install: package already present: luaotfload
tlmgr.pl install: package already present: makeindex
tlmgr.pl install: package already present: mathspec
tlmgr.pl install: package already present: metafont
tlmgr.pl install: package already present: mfware
tlmgr.pl install: package already present: natbib
tlmgr.pl install: package already present: oberdiek
tlmgr.pl install: package already present: titling
tlmgr.pl install: package already present: tools
tlmgr.pl install: package already present: upquote
tlmgr.pl install: package already present: url
tlmgr.pl install: package already present: xetex
tlmgr.pl install: package already present: xkeyval
tlmgr.pl install: package already present: zapfding
Warning: conflicting [pdf]tex program found on the system path in C:\Users\Davi Bicudo\AppData\Roaming\TinyTeX\bin\win32; not fixable in user mode.
Use of uninitialized value in bitwise or (|) at C:\Users\DAVIBI~1\AppData\Roaming\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 1479.
tlmgr.pl: already registered auxtree: C:/PROGRA~1/R/R-34~1.3/share/texmf
tlmgr.pl: action conf returned an error; continuing.
tlmgr.pl: An error has occurred. See above messages. Exiting.
TinyTeX installed to C:\Users\Davi Bicudo\AppData\Roaming/TinyTeX
Restart your R session and check if tinytex:::is_tinytex() is TRUE.
Warning message:
In file.remove("TinyTeX/install-tl.log") :
  cannot remove file 'TinyTeX/install-tl.log', reason 'No such file or directory'

Restarting R session...

> tinytex:::is_tinytex()
[1] FALSE

**Comment by yihui** [comment]
What does `tinytex:::texlive_root()` return? And what is your `xfun::session_info('tinytex')`?

Note that if you are using RStudio, you also need to restart it every time you install or remove TInyTeX.

**Comment by davibicudo** [comment]
Know it is working, nice :)
I have no idea what happened, since previously I had also restarted RStudio together with R, but in my last attempts I was restarting only R since the log didn't mentioned anything about RStudio. Somehow the installation was repaired in the process and now that I restarted both R and RStudio it is working. 
Thanks for the help nonetheless!
