### ISSUE TITLE
`r_texmf_path()` did not return correct result

### ISSUE THREAD

**Issue by hongyuanjia** [yihui/tinytex#60]
This seems to be similar with #22 . `r_texmf()` did not work for me even using the GitHub version. This led to the error when compiling package PDF manual which complained about missing `Rd.sty`.

```r
tinytex::r_texmf()
#> tlmgr conf auxtrees add '/usr/share/R//texmf'
#> tlmgr: already registered auxtree: /usr/share/R//texmf
#> tlmgr: action conf returned an error; continuing.
#> tlmgr: An error has occurred. See above messages. Exiting.
```

What caused this error is that [`tinytex:::r_texmf_path()`](https://github.com/yihui/tinytex/blob/446f17c1cf5fc6a33720087bacca9468f15b1642/R/tlmgr.R#L175) did not return correct path. The correct path should be `/usr/share/texmf` on my computer.

```r
tinytex:::r_texmf_path()
#> [1] "'/usr/share/R//texmf'"
```

```bash
ls -la /usr/share/R
# total 44K
# drwxr-xr-x  10 root root 4.0K 8月   1 23:21 .
# drwxr-xr-x 226 root root 4.0K 8月   8 08:58 ..
# drwxr-xr-x   2 root root 4.0K 8月   1 23:21 dictionaries
# drwxr-xr-x   2 root root 4.0K 8月   1 23:21 encodings
# drwxr-xr-x   2 root root 4.0K 8月   1 23:21 java
# drwxr-xr-x   2 root root 4.0K 8月   1 23:21 licenses
# drwxr-xr-x   2 root root 4.0K 8月   1 23:21 make
# drwxr-xr-x   2 root root 4.0K 8月   1 23:21 R
# drwxr-xr-x   3 root root 4.0K 8月   1 23:21 Rd
# drwxr-xr-x   2 root root 4.0K 8月   1 23:21 sh
```

I am using [Manjaro Linux (17.1.11)](https://manjaro.org/) and installed R using `pacman -S R`. I did not know if this is related to some specific Linux distro which did not put the `texmf` folder in the normal position.

Current workaround is to manually add R's texmf using `tlmgr_conf()`:

```r
tinytex::tlmgr_conf(c("auxtrees", "add", "/usr/share/texmf"))
#> tlmgr conf auxtrees add /usr/share/texmf
```

After that, I can compile package PDF manual successfully.

Below is my session info:

```r
devtools::session_info('tinytex')
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       Asia/Shanghai               
#>  date     2018-08-08                  
#> 
#>  package * version date       source                        
#>  tinytex   0.6.6   2018-08-08 Github (yihui/tinytex@446f17c)
#>  tools     3.5.1   2018-07-02 local                         
#>  xfun      0.3     2018-07-06 CRAN (R 3.5.1)                
```

**Comment by yihui** [comment]
I cannot do much about this issue. I guess it is specific to your Linux distro. The reason for the failure is that `R.home('share')` didn't return the correct path on your system. I just tested Ubuntu and it worked well.

Since you have found a workaround that is simple enough, I'm going to close this issue. Thanks a lot for the report and the solution!

BTW, per documentation `?R.home`, I think you may also set the environment variable `R_SHARE_DIR=/usr/share/`.

**Comment by hongyuanjia** [comment]
That is super quick response! 

Thanks for the hint! I will try that.

**Comment by yihui** [comment]
Actually I have provided a patch in this package. You may test it by

```r
# restart your R session first
devtools::install_github('yihui/tinytex')
tinytex::r_texmf('remove')
tinytex::r_texmf()
tinytex:::kpsewhich('Rd.sty')
```
