### ISSUE TITLE
Failed to compile test.tex

### ISSUE THREAD

**Issue by samawelch** [yihui/tinytex#61]
Hello,
Thanks for all your work on a more friendly and lightweight LaTeX distribution.  I'm pretty new to all this, so I apologise if I've missed anything obvious, but I've tried searching for the following error messages without any success. 

I've installed tinytex, run `tinytex:::install_tinytex()`, restarted RStudio, run `is_tinytext()` (TRUE), but when I try to run `pdflatex('test.tex')` I get an error message: 
`Error: Failed to compile test.tex.`

Looking at the log file produced I get the following:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/W32TeX) (preloaded format=pdflatex 2018.8.13)  13 AUG 2018 17:33
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**test.tex
! Emergency stop.
<*> test.tex
             
Here is how much of TeX's memory you used:
 3 strings out of 494587
 106 string characters out of 6176134
 51405 words of memory out of 5000000
 3741 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 0i,0n,0p,1b,6s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!
```

I'm running R 3.5.1, RStudio 1.1.456, tinytex 0.6.7 and Windows 8.1 with updates turned on.

**Comment by yihui** [comment]
What is test.tex?

**Comment by samawelch** [comment]
Ok, after a bit of closer investigation it looks like I was just using the function wrong. Sorry about that...
