### ISSUE TITLE
"restart your R session" is incomplete

### ISSUE THREAD

**Issue by r2evans** [yihui/tinytex#62]
Related to or continuing from #58:

I found the same symptoms (`tinytex:::is_tinytex()` returned `FALSE` after restarting R after successful installation), and they were due to the fact that R had not yet inherited the new `PATH`. This is not necessarily an R or RStudio thing, it's how the `PATH` envvar is updated and available to still-running sessions/shells.

- For RStudio, restarting the R session (via the menu or shortcut) was insufficient. Restarting RStudio fixed the symptomp.
- This is true for any IDE, really: I use emacs/ESS, and restarting emacs or just manually with something like `Sys.setenv(PATH=paste(Sys.getenv("PATH"), file.path(Sys.getenv("APPDATA"), "TinyTeX", "bin", "win32"), sep=.Platform$path.sep))`

I suggest changing the documentation (either in `install_tinytex` or in the readme/help-pages) to suggest restarting RStudio or other IDE. (You could always test that `Sys.setenv` step in `install_tinytex`, but I understand if you'd rather not mess with users' envvars.)

**Comment by yihui** [comment]
When in RStudio, `install_tinytex()` does tell users to restart RStudio:
https://github.com/yihui/tinytex/blob/2dc3cf0672146c1eb41354b051da9a4dd0d93335/R/install.R#L137

I'll tweak the message to remind users of restarting their editor/IDE. Thanks!

**Comment by yihui** [comment]
Okay, I have moved the message to the end of the installation process.
