### ISSUE TITLE
tinytex not downloading as expected 

### ISSUE THREAD

**Issue by elaineq47** [yihui/tinytex#63]
Hi Yihui 
I have faced an issue in installing tinytex through R. 

I learned about using tinytex to compile rmarkdown PDF from your earlier post #1285. 

So I first uninstalled Miktex and then run 
`tinytex::install_tinytex()`

But the program just keeps on running without proceeding further. I'm expecting it to take a few minutes, not hours, so I had to force quit every time I try. Here's what's on the console: 

> tinytex::install_tinytex()
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
Content type 'application/zip' length 19775481 bytes (18.9 MB)
downloaded 18.9 MB

trying URL 'https://github.com/yihui/tinytex/raw/master/tools/pkgs-custom.txt'
trying URL 'https://github.com/yihui/tinytex/raw/master/tools/pkgs-custom.txt'
Content type 'text/plain; charset=utf-8' length 275 bytes
downloaded 275 bytes

trying URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile'
trying URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile'
Content type 'text/plain; charset=utf-8' length 295 bytes
downloaded 295 bytes

Starting to install TinyTeX to C:\Users\nh926qj\AppData\Roaming/TinyTeX. It will take a few minutes.
PATH=C:\Users\nh926qj\AppData\Local\Temp\RtmpWm3UuC\install-tl-20180814\tlpkg\tlperl\bin;C:\Users\nh926qj\Documents\R\R-3.4.0\bin\i386;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Perl64\site\bin;C:\Perl64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Common Files\Hitachi ID\;C:\Program Files\Common Files\Hitachi ID\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\nh926qj\AppData\Local\Microsoft\WindowsApps;C:\Users\nh926qj\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\
"C:\Users\nh926qj\AppData\Local\Temp\RtmpWm3UuC\install-tl-20180814\install-tl" -profile=../texlive.profile
Automated TeX Live installation using profile: ../texlive.profile

session info: 
R version 3.4.0 (2017-04-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tinytex_0.6

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0    xfun_0.3   

Any ideas? This is my first time asking a question on GitHub, please let me know if you need any additional info.

**Comment by elaineq47** [comment]
Hi, 
 Update to my issue. I waited about an hour this time and the installation stopped running. HOWEVER tinytex was still not installed. 

>R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

>R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

>R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

>Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
```

>tinytex::install_tinytex()
MiKTeX-pdfTeX 2.9.6668 (1.40.19) (MiKTeX 2.9.6730 64-bit)
Copyright (C) 1982 D. E. Knuth, (C) 1996-2018 Han The Thanh
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.56.1; using libcurl/7.56.1 WinSSL
compiled with expat version 2.2; using expat_2.2.0
compiled with jpeg version 9.2
compiled with liblzma version 50020032; using 50020032
compiled with libpng version 1.6.34; using 1.6.34
compiled with libressl version LibreSSL 2.5.3; using LibreSSL 2.5.3
compiled with MiKTeX Application Framework version 2.6636; using 2.6636
compiled with MiKTeX Core version 7.6745; using 7.6745
compiled with MiKTeX Archive Extractor version 1.6300; using 1.6300
compiled with MiKTeX Package Manager version 3.6727; using 3.6727
compiled with poppler version 0.60.1
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.11; using 1.2.11
Error: Detected an existing LaTeX distribution (e.g., pdftex is at C:\Users\nh926qj\AppData\Local\Programs\MIKTEX~1.9\miktex\bin\x64\pdftex.exe). You have to uninstall it, or use install_tinytex(force = TRUE) if you are sure TinyTeX can override it (e.g., you are a PATH expert or installed TinyTeX previously).
> tinytex:::is_tinytex()
[1] FALSE
> tinytex::install_tinytex()
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
Content type 'application/zip' length 19775481 bytes (18.9 MB)
downloaded 18.9 MB

trying URL 'https://github.com/yihui/tinytex/raw/master/tools/pkgs-custom.txt'
trying URL 'https://github.com/yihui/tinytex/raw/master/tools/pkgs-custom.txt'
Content type 'text/plain; charset=utf-8' length 275 bytes
downloaded 275 bytes

trying URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile'
trying URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile'
Content type 'text/plain; charset=utf-8' length 295 bytes
downloaded 295 bytes

Starting to install TinyTeX to C:\Users\nh926qj\AppData\Roaming/TinyTeX. It will take a few minutes.
PATH=C:\Users\nh926qj\AppData\Local\Temp\RtmpWm3UuC\install-tl-20180814\tlpkg\tlperl\bin;C:\Users\nh926qj\Documents\R\R-3.4.0\bin\i386;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Perl64\site\bin;C:\Perl64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Common Files\Hitachi ID\;C:\Program Files\Common Files\Hitachi ID\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\nh926qj\AppData\Local\Microsoft\WindowsApps;C:\Users\nh926qj\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\
"C:\Users\nh926qj\AppData\Local\Temp\RtmpWm3UuC\install-tl-20180814\install-tl" -profile=../texlive.profile
Automated TeX Live installation using profile: ../texlive.profile
cannot contact mirror.ctan.org, returning a backbone server!
Loading http://www.tex.ac.uk/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb
C:\Users\nh926qj\AppData\Local\Temp\RtmpWm3UuC\install-tl-20180814\install-tl: TLPDB::from_file could not download http://www.tex.ac.uk/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb;
C:\Users\nh926qj\AppData\Local\Temp\RtmpWm3UuC\install-tl-20180814\install-tl: maybe the repository setting should be changed.
TinyTeX installed to C:\Users\nh926qj\AppData\Roaming/TinyTeX
Restart your R session and check if tinytex:::is_tinytex() is TRUE.
Warning messages:
1: In download.file(url, output, ..., method = method) :
  URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip': status was 'Couldn't connect to server'
2: In download.file(url, output, ..., method = method) :
  URL 'https://github.com/yihui/tinytex/raw/master/tools/pkgs-custom.txt': status was 'Couldn't connect to server'
3: In download.file(url, output, ..., method = method) :
  URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile': status was 'Couldn't connect to server'
4: In file.remove("TinyTeX/install-tl.log") :
  cannot remove file 'TinyTeX/install-tl.log', reason 'No such file or directory'
5: running command '"bin/win32/tlmgr" install latex-bin xetex amscls amsfonts amsmath bibtex booktabs caption dvipdfmx ec etoolbox fancyvrb fontspec framed geometry graphics graphics-def gsftopk hyperref ifluatex ifxetex latexmk lm luaotfload makeindex mathspec metafont mfware natbib oberdiek titling tools upquote url xkeyval zapfding' had status 127 
6: running command '"bin/win32/tlmgr" path add' had status 127 
7: running command '"bin/win32/tlmgr" conf auxtrees add "C:/Users/nh926qj/DOCUME~1/R/R-34~1.0/share/texmf"' had status 127 
`

```

after restarting the session, tinytex is however not installed. 

`> library(tinytex)
Warning message:
package ‘tinytex’ was built under R version 3.4.4 
> tinytex:::is_tinytex()
[1] FALSE
`

anyone encountered the same issue before? Many thanks!

**Comment by yihui** [comment]
https://yihui.name/tinytex/#comment-4039915586

I guess you have emailed me, posted a comment at yihui.name/tinytex, and filed an issue here. [Please do me a favor to ask your question in one place only.](https://yihui.name/en/2017/10/cross-posting/) Thanks!
