### ISSUE TITLE
texi2dvi() fails during package build: tex not found

### ISSUE THREAD

**Issue by kevinushey** [yihui/tinytex#73]
I just installed tinytex on a new macOS machine. When I try to build the Rcpp package, I get the following error output:

```
==> R CMD build Rcpp

* checking for file ‘Rcpp/DESCRIPTION’ ... OK
* preparing ‘Rcpp’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to process help pages
* building the PDF package manual
Hmm ... looks like a package
Converting Rd files to LaTeX ...Creating pdf output from LaTeX ...

Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'Rd2.tex' failed.
Output:
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.  If you want to use
this script, you'll need to install TeX (if you don't have it) or change
your PATH or TEX environment variable (if you do).  See the --help
output for more details.

For information about obtaining TeX, please see http://tug.org/texlive,
or do a web search for TeX and your operating system or distro.
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'Rd2.tex' failed.
Output:
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.  If you want to use
this script, you'll need to install TeX (if you don't have it) or change
your PATH or TEX environment variable (if you do).  See the --help
output for more details.

For information about obtaining TeX, please see http://tug.org/texlive,
or do a web search for TeX and your operating system or distro.
Error in running tools::texi2pdf()

Exited with status 1.
```

Indeed, I don't see a `tex` binary created by TinyTeX. I can of course get these installed with `tlmgr`, but would it be worth considering having this (and perhaps inconsolata) installed by default?

**Comment by yihui** [comment]
This is FAQ 6: https://yihui.name/tinytex/faq/

I don't know whether I should add these packages by default. Only R package developers need them. Let me check the total size of these packages first.

**Comment by kevinushey** [comment]
Sorry! I should have checked that first.

These all appear to be small packages -- I don't think it would hurt to install them by default, but I can understand why you want to keep tinytex as tiny as possible.

**Comment by yihui** [comment]
They are about 6Mb. Probably not too bad compared to the current default size of TinyTeX (150Mb). Let me just add them in the default installation, and save an FAQ (I'm never big fan of FAQ--nobody reads FAQ, and FAQ often indicates confusing problems).

**Comment by kevinushey** [comment]
Thank you Yihui :-)

**Comment by eschen42** [comment]
@yihui Any hints for what I am doing wrong?

 I have installed tinytex either from CRAN or 
with
```r
devtools::install_github("yihui/tinytex")
```
and it generally works as expected.

However, when I invoke
```r
devtools::build_manual()
```
I am still having issues with
```
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.
```
even when I have
```r
Sys.setenv(PATH = paste0(Sys.getenv("PATH"),":/home/rstudio/.TinyTeX/bin/x86_64-linux/"))
```
in my `~/.Rprofile` and when texi2dvi is installed at
`/usr/bin/texi2dvi` and regardless of whether it is symlinked to `/usr/local/bin/texi2dvi`

**Comment by rwang14** [comment]
> @yihui Any hints for what I am doing wrong?
> 
> I have installed tinytex either from CRAN or
> with
> 
> ```r
> devtools::install_github("yihui/tinytex")
> ```
> 
> and it generally works as expected.
> 
> However, when I invoke
> 
> ```r
> devtools::build_manual()
> ```
> 
> I am still having issues with
> 
> ```
> You don't have a working TeX binary (tex) installed anywhere in
> your PATH, and texi2dvi cannot proceed without one.
> ```
> 
> even when I have
> 
> ```r
> Sys.setenv(PATH = paste0(Sys.getenv("PATH"),":/home/rstudio/.TinyTeX/bin/x86_64-linux/"))
> ```
> 
> in my `~/.Rprofile` and when texi2dvi is installed at
> `/usr/bin/texi2dvi` and regardless of whether it is symlinked to `/usr/local/bin/texi2dvi`

I have the same issue. Have you fixed it?
