### ISSUE TITLE
How to install documentation?

### ISSUE THREAD

**Issue by kgrossjo** [yihui/tinytex#78]
Believe it or not, I seem to be one of the five people who actually invoke `texdoc` to get some information.  (Actually, the `ngerman` package told me what to read so that I can install German hyphenation patterns, so I tried to read that and discovered that there is no documentation...)

Is there a way to install package documentation in TinyTeX?

I was about to clone the repo to edit the profile to install documentation, as well.  Then I saw that the scripts are all hard-wired to download stuff, they are not designed to be run from a local clone.

**Comment by yihui** [comment]
Change this option to 1: https://github.com/yihui/tinytex/blob/db8edf02d63d419db5d9d7e97db2831df81b25d4/tools/texlive.profile#L14

and change the URLs in the scripts to local paths.

But as I said in the FAQ 4: https://yihui.name/tinytex/faq/

> [...] The address bar of your web browser is the most convenient documentation: type and search.

If you do that, you will almost surely find the documentation of `ngerman`: https://ctan.org/pkg/ngerman I don't see any point of installing documentation locally, unless you plan to work in an environment without Internet for a long time (even in that case, you can still download the documentation in advance).
