### ISSUE TITLE
tinytex not working

### ISSUE THREAD

**Issue by Oscarrrod** [yihui/tinytex#81]
hello,
I have installed tinytex but I cannot produce any pdf; could you help me, please?
when I try "knit to pdf" in Rstudio I get:
entering extended mode
tlmgr search --file --global "/multirow.sty"
! LaTeX Error: File `multirow.sty' not found.

! Emergency stop.
<read *> 

Error: Failed to compile medi_report.tex. See medi_report.log for more info.
Execution halted

I was wondering if the problem is that I am not administrator and I cannot write in the root dir for tinytex so I moved to a directory that I can write and then used:
tinytex::use_tinytex(from = "C:/***/TinyTeX")
but it is not working every time that I ask it comes back that the root is ***\\Roaming\\TinyTeX

So if you have a minute, I would love for you to have a look.
Thanks

**Comment by yihui** [comment]
TinyTeX doesn't require admin privileges.

What does `tinytex::tlmgr_search("/multirow.sty")` return?

**Comment by Oscarrrod** [comment]
Thank you for the quick reply, I am completely new to this so I thought that maybe it was the reason.
The reply to your comment:
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

**Comment by Oscarrrod** [comment]
sorry, continuation:

No connection to the internet.
Unable to download the checksum of the remote TeX Live database,
but found a local copy so using that.

You may want to try specifying an explicit or different CTAN mirror;
see the information and examples for the -repository option at
http://tug.org/texlive/doc/install-tl.html
(or in the output of install-tl --help).

tlmgr.pl: package repository http://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: unknown)
multirow:
	texmf-dist/tex/latex/multirow/multirow.sty

as a comment: internet is working

**Comment by yihui** [comment]
Then what does `tinytex::tlmgr_install("multirow") return?

**Comment by Oscarrrod** [comment]
```
tlmgr install multirow
No connection to the internet.
Unable to download the checksum of the remote TeX Live database,
but found a local copy so using that.

You may want to try specifying an explicit or different CTAN mirror;
see the information and examples for the -repository option at
http://tug.org/texlive/doc/install-tl.html
(or in the output of install-tl --help).

tlmgr.pl: package repository http://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: unknown)
[1/1, ??:??/??:??] install: multirow [3k]
TLPDB::_install_package: downloading did not succeed
tlmgr.pl: package log updated: C:/*/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
```

Thanks,

**Comment by yihui** [comment]
Are you using a proxy to access internet?

**Comment by Oscarrrod** [comment]
I think so, there is a configuration script in the internet connection, it is my work connection

**Comment by yihui** [comment]
Does your R have access to internet? If it does, do you know how the proxy was configured for R? (Normally you use the environment variables like `http_proxy` / `ftp_proxy`, etc).

For TeX Live, you may write the proxy info in `~/.wgetrc`: https://www.gnu.org/software/wget/manual/html_node/Proxies.html

**Comment by Oscarrrod** [comment]
Yes, I can install R packages without problem, I had to ask IT to install it as this I am not administrator but no problems with packages as they gave me admin rights to the R folder,
that was I think your package is a good idea: get latex as a kind of R package; but it seems the problem are the proxies: this weekend tried to install miktex and the installer downloaded but when it tried to get the software from the web it had the same problem so it seems that I cannot install anything that is not on the list.
Sorry about for using your time, I am kind of starting so didn't know that. Thanks,

**Comment by yihui** [comment]
No worries. It depends on whether you know the proxy server and are able to use it to download anything (e.g. try `xfun::download_file('https://cran.rstudio.com/src/contrib/tinytex_0.9.tar.gz', tempfile(), mode = 'wb')`). If yes, I guess I can help you make TinyTeX work with your proxy.

**Comment by Oscarrrod** [comment]
Thanks for that, but it says couldn't connect to server.
I will go to word and then save as pdf, not ideal but it would work,
I will keep tinytex because in some has worked and I still think it is a good idea,
cheers

**Comment by yihui** [comment]
The last resort could be that you install TinyTeX on a Flash drive on a Windows machine that has direct access to the internet, install the missing LaTeX packages, and use TinyTeX from the Flash drive: https://yihui.name/en/2018/08/tinytex-flash-drive/

It is hard to use TinyTeX if it doesn't have internet access. Some documents may just work fine, but for documents that require additional packages, it will fail.

**Comment by Oscarrrod** [comment]
Thanks for that,

**Comment by bailliecharles** [comment]
Hi 
You mentioned above that you could make tinytex work with a proxy. Could you advise please? I've checked I get 200 status when using GET request through R. 

Thanks,
C

> No worries. It depends on whether you know the proxy server and are able to use it to download anything (e.g. try `xfun::download_file('https://cran.rstudio.com/src/contrib/tinytex_0.9.tar.gz', tempfile(), mode = 'wb')`). If yes, I guess I can help you make TinyTeX work with your proxy.

**Comment by yookatel** [comment]
hi there, i get the same issue:
> tinytex::tlmgr_search("/multirow.sty")
tlmgr search --file --global "/multirow.sty"
The system cannot find the path specified.
> tinytex::tlmgr_install("multirow")
tlmgr install multirow
The system cannot find the path specified.
tlmgr update --self
tlmgr install multirow
The system cannot find the path specified.
> xfun::download_file('https://cran.r-project.org/src/contrib/Archive/tinytex/tinytex_0.9.tar.gz', tempfile(), mode = 'wb'))
Error: unexpected ')' in "xfun::download_file('https://cran.r-project.org/src/contrib/Archive/tinytex/tinytex_0.9.tar.gz', tempfile(), mode = 'wb'))"
> xfun::download_file('https://cran.r-project.org/src/contrib/Archive/tinytex/tinytex_0.9.tar.gz', tempfile(), mode = 'wb')).
Error: unexpected ')' in "xfun::download_file('https://cran.r-project.org/src/contrib/Archive/tinytex/tinytex_0.9.tar.gz', tempfile(), mode = 'wb'))"
> xfun::download_file('https://cran.r-project.org/src/contrib/Archive/tinytex/tinytex_0.9.tar.gz', tempfile(), mode = 'wb')
trying URL 'https://cran.r-project.org/src/contrib/Archive/tinytex/tinytex_0.9.tar.gz'
Content type 'application/x-gzip' length 21012 bytes (20 KB)
downloaded 20 KB 

tried everything but still doesnt knit

this is the error term
The system cannot find the path specified.
! LaTeX Error: File `multirow.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile HW1_Part3_NA_KJY.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See HW1_Part3_NA_KJY.log for more info.
Execution halted


could you kindly help

**Comment by cderv** [comment]
please open a new issue instead of commenting on an old one when it is not directly related. 

> ! LaTeX Error: File `multirow.sty' not found.

Do you use TinyTeX distribution or another like MikTeX ? 

It seems you are missing a file. **tinytex** should have found it and install it for you. 

```r
> tinytex::parse_packages(files = "multirow.sty")
tlmgr search --file --global "/multirow.sty"
[1] multirow
```

You can install this missing package with 
```r
tinytex::tlmgr_install("multirow")
```

This should work if you use a distribution with `tlmgr`. Otherwise, just install the **multirow** LaTeX package. 

Hope it helps
