### ISSUE TITLE
Chinese can't be displayed on ggplot2 output in a chunk

### ISSUE THREAD

**Issue by shawnxu1111** [yihui/tinytex#83]
This is my setting of the Rmarkdown file 

> title: "XX数据质量分析"
author: "xusheng"
date: "2018/11/13"
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
    dev: cairo_pdf
classoption: "hyperref,"

dev: cairo_pdf is used to block many errors like these below:

> ## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
>## 'mbcsToSbcs' 里转换 ' 鐧介 ? 婀栧皬鍖 <U+FFFD>' 出错： <e7> 代替了 dot
>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
>## 'mbcsToSbcs' 里转换 ' 鐧介 ? 婀栧皬鍖 <U+FFFD>' 出错： <99> 代替了 dot
>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
>## 'mbcsToSbcs' 里转换 ' 鐧介 ? 婀栧皬鍖 <U+FFFD>' 出错： <bd> 代替了 dot
>......

This is the code for the graph below:
````{r pic, fig.width=7, fig.height=6, echo=FALSE}
pic_er=ggplot(matrix_er, aes(x = matrix_er$cat, y = matrix_er$er, fill = matrix_er$dn)) + 
  geom_bar(position =position_dodge2(padding=0), stat="identity") + 
  xlab("Catagory")+ylab("Effective Rate") + scale_fill_economist(name=NULL)+
  ggtitle("The Comparison Of Effective Rates \nBased On Districts And Catagories") + 
  geom_text(aes(label=percent(matrix_er$er)),position = position_dodge(.9),size=rel(2),hjust=1.2,vjust=0.3) + 
  coord_flip() + 
  theme_economist(base_family="Verdana") + theme(axis.title = element_text(size = rel(1.5),face="bold"), 
                                                 legend.text =element_text(size = rel(0.8)),legend.position = "right")
pic_er
````
Then the picture is shown as below:
![1](https://user-images.githubusercontent.com/6002262/48456911-bd16dd80-e7fb-11e8-8f35-2da0b196d2f5.PNG)

Those Chinese words on the legend are not displayed as expected on the right side, replaced by square,square,square!

**Comment by dfrankow** [comment]
Using knitr, I get this error when I had a unicode character:

```
! Package inputenc Error: Unicode character 年 (U+5E74)
(inputenc)                not set up for use with LaTeX.

Try other LaTeX engines instead (e.g., xelatex) if you are using pdflatex. For R Markdown users, see https://bookdown.org/yihui/rmarkdown/pdf-document.html
```

So I wonder if the ultimate solution would be to base TinyTeX on a different LaTeX engine?

**Comment by dfrankow** [comment]
For posterity: I found I can use xelatex in tinytex, which can show CJK languages.

**Comment by yihui** [comment]
@dfrankow That's what the error message told you.

**Comment by dfrankow** [comment]
I did not realize xelatex was already in tinytex (or could be gotten through it).
