### ISSUE TITLE
Issues with Rd2pdf

### ISSUE THREAD

**Issue by aravind-j** [yihui/tinytex#84]
I am using `tintytex` in windows. For R package vignettes, it is working great. But when creating R documentation pdf file using `Rd2pdf`, all the **>** symbol is replaced by **¿**.

```
path <- find.package("mypackage")
system(paste(shQuote(file.path(R.home("bin"), "R")),
             "CMD", "Rd2pdf", shQuote(path)))
```
There are several warnings as follows

- Package hyperref Warning: Option `hyperindex' has already been used,
(hyperref)                setting the option has no effect on input line
- No file Rd2.aux.
- No file Rd2.ind.
- Underfull \hbox (badness 10000) in paragraph at lines
- Package rerunfilecheck Warning: File `Rd2.out' has changed.
- Overfull \hbox (9.5038pt too wide) in paragraph at lines
- LaTeX Font Warning: Font shape `OT1/zi4/m/it' undefined
(Font)              using `OT1/zi4/m/n' instead on input line 5.
- LaTeX Font Warning: Some font shapes were not available, defaults substituted.
- Package rerunfilecheck Warning: File `Rd2.out' has changed.
(rerunfilecheck)                Rerun to get outlines right
(rerunfilecheck)                or use package `bookmark'.

**Comment by yihui** [comment]
When did you install TinyTeX? If you installed it long time ago, run this:

```r
tinytex::tlmgr_install(readLines('https://github.com/yihui/tinytex/raw/master/tools/pkgs-custom.txt'))
```

**Comment by aravind-j** [comment]
I installed it only last week. I tried running the command, but got the message that all the packages already exist. 

I tried `tinytex::tlmgr_update(all = TRUE)`, it updated `babel` but still problem persists.

**Comment by yihui** [comment]
I have never tested `R CMD Rd2pdf` myself, so I don't have an idea here. I don't have time for this task, either, so if you can figure out which LaTeX should be installed, I'd welcome a pull request; otherwise here is a blind shot in the dark (to install some packages that I installed for myself):

```r
tinytex::tlmgr_install(readLines('https://github.com/yihui/tinytex/raw/master/tools/pkgs-yihui.txt'))
```

**Comment by aravind-j** [comment]
Installing these packages fixed the issue with > being replaced by ¿. However several other issues do persisit.
I'll keep digging to find which of these packages worked, and any other additional packages required to avoid the latex errors.
