### ISSUE TITLE
error converting to loadable format

### ISSUE THREAD

**Issue by 2017rainman** [yihui/tinytex#85]
ubuntu 18.04系统。装完tinytex，然后装lyx-2.3.1，在lyx文档里插入pdf或eps格式的图片时，出现“error converting to loadable format”的提示。虽然lyx文档能正常编译，但无法在lyx文档中显示图片。其他如jpg、png格式的图片则没有这种不显示图片的情况。该怎么解决？

**Comment by yihui** [comment]
`lyx error converting to loadable format` 放狗一搜：https://tex.stackexchange.com/q/326244/9128

**Comment by 2017rainman** [comment]
谢谢！跟tinytex没关系，so sorry!是Ubuntu中ImageMagick的问题。解决办法：
In `/etc/ImageMagick-6/policy.xml', comment out the lines like
'<policy domain="coder" rights="none" pattern="(...)" />'
或者：将'rights="none"'改为'rights="read|write"'

[https://tex.stackexchange.com/questions/462223/lyx-error-converting-to-loadable-format-for-pdfs-under-ubuntu?noredirect=1]
[](url)
[](https://www.mail-archive.com/lyx-devel@lists.lyx.org/msg206999.html)

**Comment by yihui** [comment]
原来如此，这问题比我想象的要复杂一点。谢谢分享解决方案！
