### ISSUE TITLE
mptopdf not symlinked to /usr/local/bin

### ISSUE THREAD

**Issue by espinielli** [yihui/tinytex#86]
I have found that `mptopdf` is not symlinked to `/usr/loca/bin` (I am on OSX) as it should, at least according to what written in [TinyTex home page](https://yihui.name/tinytex/).

(Same for `mpost`...but I am not using it so I do not know whether this is needed...)

In the hope to help and provide a PR, I tried to find where this is done in the installation script but failed miserably. Sorry to only report the problem and not the solution too.

**Comment by yihui** [comment]
Not reproducible to me on macOS:

```
> Sys.which('mptopdf')
mptopdf 
     "" 
> tinytex::tlmgr_install('mptopdf')
tlmgr install mptopdf
tlmgr: package repository http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet (not verified: gpg unavailable)
[1/2, ??:??/??:??] install: mptopdf.x86_64-darwin [1k]
[2/2, 00:00/00:00] install: mptopdf [38k]
running mktexlsr ...
done running mktexlsr.
regenerating fmtutil.cnf in /Users/yihui/Library/TinyTeX/texmf-dist
running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --byfmt mptopdf ...
done running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --byfmt mptopdf.
tlmgr: package log updated: /Users/yihui/Library/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr path add
> Sys.which('mptopdf')
                 mptopdf 
"/usr/local/bin/mptopdf" 
```

If you use TinyTeX from R, you should install LaTeX packages via `tinytex::tlmgr_install()`, which will do the symlinks for you. If you don't use R, you'll have to run `tlmgr path add` after `tlmgr install mptopdf`.

**Comment by espinielli** [comment]
Installing via `tinytex::tlmgr_install()` solved the problem...in fact I was trying to use it from outside R, so the `tlmgr path add` was missing.
Thanks a million!

(I did uninstall my previous TL installation in favor to using TinyTex bot inside and outside my R work)

**Comment by yihui** [comment]
You are welcome!
