### ISSUE TITLE
Unnecessary warning about no missing packages.

### ISSUE THREAD

**Issue by davidhunterwalsh** [yihui/tinytex#9]
I'm running the developer version of rmarkdown so that missing LaTeX packages are automatically installed, and while it works great, I notice that if there's any compilation error of any kind such that a log is generated, the rmarkdown output says, inter alia: `I was unable to find any missing LaTeX packages from the error log file.log.` I imagine this should be suppressed for brevity's sake.

**Comment by yihui** [comment]
Done. Thanks for the report!

**Comment by davidhunterwalsh** [comment]
Wow. Nice.
