### ISSUE TITLE
Error using tinytex in portable mode, with tinytex::use_tinytex(). Can't knit to PDF.

### ISSUE THREAD

**Issue by matacarlos01** [yihui/tinytex#91]
Moved from https://github.com/rstudio/rstudio/issues/4096

LaTex seems to have an issue with weird folder naming in the company I work for, which includes a '$' sign. Error in 'kpathsea'.  Is there a workaround?    I made some a nice report in HTML but now people want it in PDF. Cheers!

##System details
RStudio Edition : Desktop
RStudio Version : 1.1.456
OS Version      :  Windows 10
R Version       :  3.5.1
Steps to reproduce the problem
I used tinytex::copy_tinytex() to create a copy of tinytex, then used tinytex::use_tinytex() to set up my R Studio to create PDFs.

##Describe the problem in detail
I get this error:

tinytex::use_tinytex()
warning: kpathsea: //QSR-FP23.YWH.LOCAL/home-mqo-1$/User/My Documents: Unrecognized variable construct `$/'.
Use of uninitialized value in bitwise or (|) at S:\Applications\SUBSUR~1\Useful Software\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 1482.

Restart R and your editor and check if tinytex::tinytex_root() points to S:/Applications/Subsurface_Tools/Useful Software/TinyTeX

The tinytex::tinytex_root() command shows the right folder. But Rstudio doesn't create the PDF.

When I attempt to knit my R Markdown to PDF, I keep getting the same error all the time:
"No TeX installation detected (TeX is required to create PDF output). You should install a recommended TeX distribution for your platform: ........"

##Describe the behavior you expected
I expected to be able to knit my R Markdown document to PDF.

Output of sessionInfo():
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 LC_CTYPE=English_United States.1252 LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C LC_TIME=English_United States.1252

attached base packages:
[1] stats graphics grDevices utils datasets methods base

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1 rstudioapi_0.8 yaml_2.2.0 tinytex_0.9 xfun_0.4

**Comment by yihui** [comment]
Did you restart RStudio? Is `S:/` your portable device? If you print `Sys.getenv("PATH")`, do you see `S:/Applications/Subsurface_Tools/Useful Software/TinyTeX/bin/win32/` in it?

**Comment by matacarlos01** [comment]
Hi Yihui,

Nice to meet you. I'm a fan of your work!

- I have restarted R studio several times

- S:/    is a network folder at work.

- I have all the software in portable mode to avoid IT headaches :-)

- Yes,  Sys.getenv("PATH") has  S:/Applications/Subsurface_Tools/Useful Software/TinyTeX/bin/win32/ in it

First time using GitHub.  Fan of your work! :smiley:

**Comment by yihui** [comment]
So you mean you used `tinytex::copy_tinytex()` to copy TinyTeX from `S:/` to your portable device. Did this succeed? Is TinyTeX on your portable device now?

Then you used `tinytex::use_tinytex()` and ran into an error. You may see `#2` in the post https://yihui.name/en/2018/08/tinytex-flash-drive/.

If that still doesn't work, you'll have to know how to modify the `PATH` variable of your system, and add the path of the directory of `tlmgr.bat` to `PATH`.

**Comment by matacarlos01** [comment]
I installed TinyTeX in my personal laptop, then used tinytex::copy_tinytex()  to copy to a Google Drive folder.

Then I downloaded from Google drive to a folder at work: S:/Applications/Subsurface_Tools/Useful Software/TinyTeX

Then I used tinytex::use_tinytex() and ran into the error.

I tried the different options in your link and still get the error.

So weird... especially the bit about LaTeX and the 'kpathsea'  accessing the 'My Documents' folder. Not sure what it means..

Will dig into the 'tlmgr.pl' file mentioned in the error message and see if I spot the problem.

**Comment by yihui** [comment]
You have two options:

1. (Recommended) Add `S:/Applications/Subsurface_Tools/Useful Software/TinyTeX/bin/win32` to the environment variable `PATH` of your system (use `;` as the delimiter).

2. Or set this option in R:

```r
options(tinytex.tlmgr.path = 'S:/Applications/Subsurface_Tools/Useful Software/TinyTeX/bin/win32/tlmgr.bat')
```

**Comment by matacarlos01** [comment]
It is working now after setting the options! A million thanks!
