### ISSUE TITLE
Rmd knitter with Miktex on windows: pdf compilation fails system2(..., stdout = FALSE, stderr = FALSE)

### ISSUE THREAD

**Issue by samuszz** [yihui/tinytex#95]
It seems my issue has already occured (found a comit on tinytex  and lost it ... sorry)
err log in R Markdown tab: 
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS pdf_template.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output pdf_template.tex --template "C:\Users\Sacha Muszlak\R\win-library\3.5\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" 
Erreur : Failed to compile pdf_template.tex.
De plus : Warning message:
In system2(..., stdout = FALSE, stderr = FALSE) :
  'CreateProcess' a échoué au lancement de 'C:\Users\Sacha Muszlak\tools\texmfs\install\miktex\bin\pdflatex.exe -halt-on-error -interaction=batchmode "pdf_template.tex"'
Exécution arrêtée

the tex file compile fine with Xelatex in texmaker.  Changing to xelatex in Rstudio isn't  taken into account

Theses are my version of some packages I feel are implicated : 
> packageVersion("knitr")
[1] ‘1.21’
> packageVersion("tinytex")
[1] ‘0.10’
>

**Comment by yihui** [comment]
Could you uninstall MiKTeX and try TinyTeX instead? https://bookdown.org/yihui/rmarkdown/installation.html
